### ISSUE TITLE
No structure pdb/psf file was generated

### ISSUE THREAD

**Issue by Grad1029** [Acellera/htmd#1063]
Hello,

I am running the following script to build a system of a protein on a model membrane:

```py

params = ['/home/anastasia/Desktop/membrane_alt/toppar/par_all36m_prot.prm', 
...                                   '/home/anastasia/Desktop/membrane_alt/toppar/par_all36_lipid.prm',
...                                   
...                                   '/home/anastasia/Desktop/membrane_alt/toppar/par_all36_cgenff.prm',
...                                   '/home/anastasia/Desktop/membrane_alt/toppar/par_all36_na.prm',
...                                   '/home/anastasia/Desktop/membrane_alt/toppar/par_all36_carb.prm']
>>> topos = ['/home/anastasia/Desktop/membrane_alt/toppar/top_all36_na.rtf', 
...                                 '/home/anastasia/Desktop/membrane_alt/toppar/top_all36_prot.rtf', '/home/anastasia/Desktop/membrane_alt/toppar/top_all36_carb.rtf',
'/home/anastasia/Desktop/membrane_alt/toppar/toppar_water_ions.str']
>>> streams =  ['/home/anastasia/Desktop/membrane_alt/toppar/stream/lipid/toppar_all36_lipid_prot.str',
... '/home/anastasia/Desktop/membrane_alt/toppar/stream/na/toppar_all36_na_nad_ppi.str',
... '/home/anastasia/Desktop/membrane_alt/toppar/stream/carb/toppar_all36_carb_glycolipid.str', 
...                                    '/home/anastasia/Desktop/membrane_alt/toppar/stream/prot/toppar_all36_prot_modify_res.str',           '/home/anastasia/Desktop/membrane_alt/toppar/stream/cphmd/protpatch_protein_toppar36.str',"/home/anastasia/Desktop/membrane_alt/toppar/stream/prot/toppar_all36_prot_na_combined.str","/home/anastasia/Desktop/membrane_alt/toppar/stream/lipid/PBUD.str","/home/anastasia/Desktop/membrane_alt/toppar/stream/lipid/toppar_all36_lipid_inositol.str"]
>>> protein_charmm=charmm.build(protein, aliasresidues=al, outdir='build_charmm0',param=params, topo=topos, stream=streams, caps={"AS1": ['first NTERP', 'last CTER'], "AS2":['first NTER', 'last CTER']}, ionize=True, saltconc=0.15)
`
and I get the following error:
2023-06-07 22:27:44,115 - htmd.builder.builder - WARNING - Segments ['AS1' 'AS2'] contain both protein and non-protein atoms. Please assign separate segments to them or the build procedure might fail.
2023-06-07 22:27:44,418 - htmd.builder.charmm - INFO - Writing out segments.
2023-06-07 22:28:30,832 - htmd.builder.builder - INFO - 0 disulfide bonds were added
2023-06-07 22:28:31,399 - htmd.builder.charmm - INFO - Starting the build.
2023-06-07 22:28:31,584 - htmd.builder.charmm - WARNING - Failed to set coordinates for 1 atoms.
2023-06-07 22:28:31,584 - htmd.builder.charmm - WARNING - Please check /home/anastasia/Desktop/membrane_alt/build_charmm0/log.txt for further information.
2023-06-07 22:28:31,584 - htmd.builder.charmm - INFO - Finished building.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anastasia/miniconda3/envs/htmd2.2.0/lib/python3.10/site-packages/htmd/builder/charmm.py", line 393, in build
    raise BuildError(
htmd.builder.builder.BuildError: 'No structure pdb/psf file was generated. Check /home/anastasia/Desktop/membrane_alt/build_charmm0/log.txt for errors in building.'

Please find attached the log file and the topology files (https://we.tl/t-fodbUStbp0)
```
Note: I have used in the past the same topology files and script and I have built and simulated a similar system

I would be grateful if you could help me

Thank you in advance

**Comment by Grad1029** [comment]
Thank you for the response, the problem solved by changing the parameter files
