### ISSUE TITLE
Input acemd 3 to acemd 4

### ISSUE THREAD

**Issue by H-EKE** [Acellera/htmd#1104]
Hi,

Before I was running in acemd 3.5.2 this input without problem 

```
#
barostat                on
barostatconstratio      on
barostatpressure        1.01325
boxsize                 221.68600463867188 221.6510009765625 175.23199462890625
coordinates             structure.pdb
cutoff                  9
minimize                5000
parameters              parameters
pme                     on
restart                 off
structure               structure.psf
switchdistance          7.5
switching               on
temperature             310
thermostat              on
thermostatdamping       1
thermostattemperature   310
timestep                2
trajectoryfile          output.xtc
trajectoryperiod        25000
atomRestraint           "segid P1 and name C CA N O or not (segid P1 or lipid or water or ions ) and noh or segid ION WAT and noh" axes xyz 
width "2" setpoints 1@0 1@20ns 0@30ns
run                     20000000

```

But now with this one in ACEMD 4

```

barostat: true
barostatconstratio: true
barostatpressure: 1.01325
boxsize:
- 221.68600463867188
- 221.6510009765625
- 175.23199462890625
coordinates: structure.pdb
cutoff: 9
extforces:
- axes: xyz
  fbwidth:
  - 2.0
  - 2.0
  - 2.0
  sel: segid P1 and name C CA N O or not (segid P1 or lipid or water or ions ) and
    noh or segid ION WAT and noh
  setpoints:
  - 1@0
  - 1@20ns
  - 0@30ns
  type: positionalRestraint
minimize: 5000
parameters: parameters
pme: true
restart: false
run: 20000000
structure: structure.psf
switchdistance: 7.5
switching: true
thermostat: true
thermostatdamping: 1
thermostattemperature: 310
timestep: 2
trajectoryfile: output.xtc
trajectoryperiod: 25000
velocities: 310
```

It is not able to recognize ```segid ION WAT and noh ```

```
2024-12-19 16:36:08,997 - moleculekit.readers - WARNING - Reading PDB file with more than 99999 atoms. Bond information can be wrong.
2024-12-19 16:36:30,966 - acemd - INFO - #
2024-12-19 16:36:30,966 - acemd - INFO - # External forces
HTMD: Logging setup failed
Traceback (most recent call last):
  File "/home/elkhaoud/.conda/envs/acemd/lib/python3.10/site-packages/moleculekit/atomselect/atomselect.py", line 276, in atomselect
    ast = parser.parse(selection, debug=_debug)
  File "/home/elkhaoud/.conda/envs/acemd/lib/python3.10/site-packages/moleculekit/ply/yacc.py", line 552, in parse
    tok = self.errorfunc(errtoken)
  File "/home/elkhaoud/.conda/envs/acemd/lib/python3.10/site-packages/moleculekit/atomselect/languageparser.py", line 546, in p_error
    raise RuntimeError(f"Syntax error at '{p.value!r}'")
RuntimeError: Syntax error at ''ION''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elkhaoud/.conda/envs/acemd/bin/acemd", line 10, in <module>
    sys.exit(_acemd_cli())
  File "/home/elkhaoud/.conda/envs/acemd/lib/python3.10/site-packages/acemd/acemd.py", line 483, in _acemd_cli
    acemd(
  File "/home/elkhaoud/.conda/envs/acemd/lib/python3.10/site-packages/acemd/acemd.py", line 541, in acemd
    system, simulation, mol, extforces = setup_acemd(
  File "/home/elkhaoud/.conda/envs/acemd/lib/python3.10/site-packages/acemd/acemd.py", line 862, in setup_acemd
    extforces_out, nonperiodic_restraints = setup_extforces(
  File "/home/elkhaoud/.conda/envs/acemd/lib/python3.10/site-packages/acemd/restraints.py", line 466, in setup_extforces
    ff = rr.setupForce(i, mol, fbrefmol, timestep)
  File "/home/elkhaoud/.conda/envs/acemd/lib/python3.10/site-packages/acemd/restraints.py", line 192, in setupForce
    atomidx = mol.atomselect(self.sel, indexes=True, guessBonds=False)
  File "/home/elkhaoud/.conda/envs/acemd/lib/python3.10/site-packages/moleculekit/molecule.py", line 995, in atomselect
    mask = atomselect(
  File "/home/elkhaoud/.conda/envs/acemd/lib/python3.10/site-packages/moleculekit/atomselect/atomselect.py", line 278, in atomselect
    raise RuntimeError(f"Failed to parse selection {selection} with error {e}")
RuntimeError: Failed to parse selection segid P1 and name C CA N O or not (segid P1 or lipid or water or ions ) and noh or segid ION WAT
 and noh with error Syntax error at ''ION''
```

What it will be the correct equivalent on ACEMD 4 ?

**Comment by stefdoerr** [comment]
Can you give a try adding parentheses to make all the and/or more explicit?
Like (....) or (....).
The syntax parser might be a bit more sensitive on such large selections

**Comment by H-EKE** [comment]
It worked , thank you!!

**Comment by H-EKE** [comment]
This format worked 

```
Atom selection: "((segid P1 and name C CA N O) or (not (segid P1 or lipid or water or ions) and noh) or (segid 'ION' 'WAT' and noh))"
```

**Comment by H-EKE** [comment]
Sorry to bother you again, but I have a few coments/questions about acedm4.

I used to use this input on acemd

```
#
barostat                on
barostatconstratio      on
barostatpressure        1.01325
boxsize                 221.68600463867188 221.6510009765625 175.23199462890625
coordinates             structure.pdb
cutoff                  9
minimize                5000
parameters              parameters
pme                     on
restart                 off
structure               structure.psf
switchdistance          7.5
switching               on
temperature             310
thermostat              on
thermostatdamping       1
thermostattemperature   310
timestep                2
trajectoryfile          output.xtc
trajectoryperiod        25000
atomRestraint           "((segid P1 and name C CA N O) or (not (segid P1 or lipid or water or ions) and noh) or (segid 'ION' 'WAT' and noh))" axes xyz width "2" setpoints 1@0 1@20ns 0@30ns
run                     20000000
```
when I parsed it to acemd4
I get this input.yaml

```
barostat: true
barostatconstratio: true
barostatpressure: 1.01325
boxsize:
- 221.68600463867188
- 221.6510009765625
- 175.23199462890625
coordinates: structure.pdb
cutoff: 9
extforces:
- axes: xyz
  fbwidth:
  - 2.0
  - 2.0
  - 2.0
  sel: ((segid P1 and name C CA N O) or (not (segid P1 or lipid or water or ions)
    and noh) or (segid 'ION' 'WAT' and noh))
  setpoints:
  - 1@0
  - 1@20ns
  - 0@30ns
  type: positionalRestraint
minimize: 5000
parameters: parameters
pme: true
restart: false
run: 20000000
structure: structure.psf
switchdistance: 7.5
switching: true
thermostat: true
thermostatdamping: 1
thermostattemperature: 310
timestep: 2
trajectoryfile: output.xtc
trajectoryperiod: 25000
velocities: 310
```


when I check acemd3 and acemd4 log files


Acemd3 log file

```
$# Pressure Control 
$
$             barostat on
$     barostatPressure 1.0132 # bar
$  barostatAnisotropic off
$   barostatConstRatio on
$      barostatConstXY off
$
$# Integration
$
$             timeStep 2.00 # fs
$           slowPeriod 1
$
$# External forces
$
$
$# Restraints
$
$        atomRestraint "segid P1 and name C CA N O or not (segid P1 or lipid or water or ions ) and noh or segid ION WAT and noh" axes XYZ width 2.000000 
setpoints  1.000000@0  1.000000@20000000fs  0.000000@30000000fs 
$
$# Run Configuration
$
$              restart off
$             minimize 5000
$                  run 20000000
# Parse force field and topology files
#   Force field: CHARMM
#   PRM file: parameters
#   PSF file: structure.psf
#
# Force field parameters
#   Number of atom parameters: 428
#   Number of bond parameters: 961
#   Number of angle parameters: 2789
#   Number of dihedral parameters: 6791
#   Number of improper parameters: 199
#   Number of CMAP parameters: 6
#
# System topology
#   Number of atoms: 798155
#   Number of bonds: 796380
#   Number of angles: 559326
#   Number of dihedrals: 498202
#   Number of impropers: 6392
#   Number of CMAPs: 1415
#
# Initializing engine
#   Version: 7.5.1
#   Plugin directory: /mnt/nfs/shared_data/ohpc_pub/libs/miniconda/4.10.3/envs/openmm1/lib/acemd3
#   Loaded plugins
#     CPU
#     PME
#     CUDA
#     CudaCompiler
#     OpenCL
#     PlumedCUDA
#     PlumedOpenCL
#     PlumedReference
#   Available platforms
#     CPU
#     CUDA
#     OpenCL
#
# Bonded interactions
#   Harmonic bond interactions
#     Number of terms: 593050
#     Number of skipped terms: 203330
#     NOTE: the skipped terms have zero force constants
#   Harmonic angle interactions
#     Number of terms: 559326
#   Urey-Bradley interactions
#     Number of terms: 293570
#   Proper dihedral interations
#     Number of terms: 596564
#     Number of skipped terms: 46378
#     NOTE: the skipped terms have zero force constants
#   Improper dihedral interations
#     Number of terms: 6147
#     Number of skipped terms: 245
#     NOTE: the skipped terms have zero force constants
#   CMAP interactions
#     Number of terms: 1415
#
# Non-bonded interactions
#   Number of exclusions: 1649579
#   Lennard-Jones terms
#     Cutoff distance: 9.000 A
#     Switching distance: 7.500 A
#   Coulombic (PME) term
#     Ewald tolerance: 0.000500
#   Using NBFIX
#   No implicit solvent
#
# Restraints
#   Reference positions: structure.pdb
#   Restraint: 1
#     Atom selection: "segid P1 and name C CA N O or not (segid P1 or lipid or water or ions ) and noh or segid ION WAT and noh"
#       Number of atoms: 11529
#       Index filename: restraint_1.sel
#   Restraint: 1
#     Type: atom
#     Axes: XYZ
#     Width: 2.000000 2.000000 2.000000 A
#     Setpoints
#       1      1.00000 kcal/mol/A^2 @ step 0
#       2      1.00000 kcal/mol/A^2 @ step 10000000
#       3      0.00000 kcal/mol/A^2 @ step 15000000
#
# Constraining hydrogen (X-H) bonds
#   Number of constrained bonds: 518739
#   Making water molecules rigid
#     Number of water molecules: 203330
# Number of constraints: 722069
#
# Creating simulation system
#   Number of particles: 798155
#   Number of degrees of freedom 1672393
#   Periodic box size: 221.686 221.651 175.232 A
#
# Integrator
#   Type: velocity Verlet
#   Step size: 2.00 fs
#   Constraint tolerance: 1.0e-06
#
# Thermostat
#   Type: Langevin
#   Target temperature: 310.00 K
#   Friction coefficient: 1.00 ps^-1
#
# Barostat
#   Type: constant ration (x/y)
#   Pressure: 1.01 bar
#
# Setting up platform: CUDA
# Interactions: 1 2 3 4 5 6 7 7 11 12 13
# Platform properties:
#   DeviceIndex: 0
#   DeviceName: NVIDIA A100 80GB PCIe
#   UseBlockingSync: false
#   Precision: mixed
#   UseCpuPme: false
#   CudaCompiler: 
#   TempDirectory: /tmp
#   CudaHostCompiler: 
#   DisablePmeStream: false
#   DeterministicForces: false
#
# Set initial positions from an input file
#
# Running minimization
#   Algorithm: CG
#   Number of steps: 5000
#
# Restraint 1: k = 1.00 changing from 0.00 to 1.00 from step 0 to 0.
# Step       Potential   
#            [kcal/mol]  
           0 124056284677865.6406
# WARNING: due to large initial force components the minimization has to switch the CPU platform
# Creating an auxilary platform for minimization
# Setting up platform: CPU
# Interactions: 1 2 3 4 5 6 7 7 11 12 13
# Platform properties:
#   Threads: 64
#   DeterministicForces: false
```
Acemd4 log file
```

2024-12-20 00:25:07,885 - acemd - INFO - # Input arguments
2024-12-20 00:25:07,885 - acemd - INFO - #   barostat: True
2024-12-20 00:25:07,885 - acemd - INFO - #   barostatanisotropic: False
2024-12-20 00:25:07,885 - acemd - INFO - #   barostatconstratio: True
2024-12-20 00:25:07,885 - acemd - INFO - #   barostatconstxy: False
2024-12-20 00:25:07,885 - acemd - INFO - #   barostatpressure: 1.01325
2024-12-20 00:25:07,885 - acemd - INFO - #   boxsize: [221.68600463867188, 221.6510009765625, 175.23199462890625]
2024-12-20 00:25:07,885 - acemd - INFO - #   coordinates: structure.pdb
2024-12-20 00:25:07,885 - acemd - INFO - #   cutoff: 9
2024-12-20 00:25:07,885 - acemd - INFO - #   device: None
2024-12-20 00:25:07,885 - acemd - INFO - #   extforces: [<acemd.restraints.PositionalRestraint object at 0x7fc06e915150>]
2024-12-20 00:25:07,885 - acemd - INFO - #   fbrefcoor: None
2024-12-20 00:25:07,885 - acemd - INFO - #   hbondconstr: None
2024-12-20 00:25:07,885 - acemd - INFO - #   hmr: None
2024-12-20 00:25:07,885 - acemd - INFO - #   hydrogenmass: 4.032
2024-12-20 00:25:07,885 - acemd - INFO - #   implicitsolvent: False
2024-12-20 00:25:07,885 - acemd - INFO - #   minimize: 5000
2024-12-20 00:25:07,885 - acemd - INFO - #   ncpus: 16
2024-12-20 00:25:07,885 - acemd - INFO - #   nnp: None
2024-12-20 00:25:07,885 - acemd - INFO - #   parameters: parameters
2024-12-20 00:25:07,885 - acemd - INFO - #   platform: CUDA
2024-12-20 00:25:07,885 - acemd - INFO - #   plumedfile: None
2024-12-20 00:25:07,885 - acemd - INFO - #   pme: True
2024-12-20 00:25:07,885 - acemd - INFO - #   precision: mixed
2024-12-20 00:25:07,885 - acemd - INFO - #   restart: False
2024-12-20 00:25:07,885 - acemd - INFO - #   rigidwater: None
2024-12-20 00:25:07,885 - acemd - INFO - #   run: 20000000
2024-12-20 00:25:07,885 - acemd - INFO - #   slowperiod: 1
2024-12-20 00:25:07,885 - acemd - INFO - #   stepzero: False
2024-12-20 00:25:07,885 - acemd - INFO - #   structure: structure.psf
2024-12-20 00:25:07,885 - acemd - INFO - #   switchdistance: 7.5
2024-12-20 00:25:07,885 - acemd - INFO - #   switching: True
2024-12-20 00:25:07,885 - acemd - INFO - #   thermostat: True
2024-12-20 00:25:07,885 - acemd - INFO - #   thermostatdamping: 1
2024-12-20 00:25:07,885 - acemd - INFO - #   thermostattemperature: 310
2024-12-20 00:25:07,885 - acemd - INFO - #   timestep: 2
2024-12-20 00:25:07,885 - acemd - INFO - #   trajectoryfile: output.xtc
2024-12-20 00:25:07,885 - acemd - INFO - #   trajectoryperiod: 25000
2024-12-20 00:25:07,885 - acemd - INFO - #   trajforcefile: None
2024-12-20 00:25:07,885 - acemd - INFO - #   trajvelocityfile: None
2024-12-20 00:25:07,886 - acemd - INFO - #   velocities: 310
2024-12-20 00:27:26,578 - acemd - INFO - #
2024-12-20 00:27:26,594 - acemd - INFO - # Initializing engine
2024-12-20 00:27:26,594 - acemd - INFO - # Version: 8.2
2024-12-20 00:27:26,594 - acemd - INFO - #   Available platforms
2024-12-20 00:27:26,594 - acemd - INFO - #     Reference
2024-12-20 00:27:26,594 - acemd - INFO - #     CPU
2024-12-20 00:27:26,594 - acemd - INFO - #     CUDA
2024-12-20 00:27:26,594 - acemd - INFO - #     OpenCL
2024-12-20 00:27:26,594 - acemd - INFO - # Selected platform: CUDA
2024-12-20 00:27:26,594 - acemd - INFO - # Platform properties
2024-12-20 00:27:26,594 - acemd - INFO - #   DeviceIndex: 0
2024-12-20 00:27:26,594 - acemd - INFO - #   DeviceName: NVIDIA A100 80GB PCIe
2024-12-20 00:27:26,594 - acemd - INFO - #   UseBlockingSync: false
2024-12-20 00:27:26,594 - acemd - INFO - #   Precision: mixed
2024-12-20 00:27:26,594 - acemd - INFO - #   UseCpuPme: false
2024-12-20 00:27:26,594 - acemd - INFO - #   CudaCompiler: 
2024-12-20 00:27:26,594 - acemd - INFO - #   TempDirectory: /tmp
2024-12-20 00:27:26,594 - acemd - INFO - #   CudaHostCompiler: 
2024-12-20 00:27:26,594 - acemd - INFO - #   DisablePmeStream: false
2024-12-20 00:27:26,594 - acemd - INFO - #   DeterministicForces: false
2024-12-20 00:27:26,594 - acemd - INFO - #
2024-12-20 00:27:26,595 - acemd - INFO - # Creating simulation system
2024-12-20 00:27:26,595 - acemd - INFO - #   Ensemble: NPT
2024-12-20 00:27:26,595 - acemd - INFO - #   Number of particles: 798155
2024-12-20 00:27:33,468 - acemd - INFO - #   Number of degrees of freedom 1672393
2024-12-20 00:27:33,468 - acemd - INFO - #   Periodic box size: 221.686 221.651 175.232 A
2024-12-20 00:27:33,468 - acemd - INFO - #
2024-12-20 00:27:33,468 - acemd - INFO - # Integrator
2024-12-20 00:27:33,468 - acemd - INFO - #   Type: LangevinMiddleIntegrator
2024-12-20 00:27:33,468 - acemd - INFO - #   Step size: 2.00 fs
2024-12-20 00:27:33,468 - acemd - INFO - #   Constraint tolerance: 1e-06
2024-12-20 00:27:33,468 - acemd - INFO - #
2024-12-20 00:27:33,468 - acemd - INFO - # Barostat
2024-12-20 00:27:33,468 - acemd - INFO - #   Pressure: 1.01325 bar
2024-12-20 00:27:33,468 - acemd - INFO - #   Temperature: 310.0 K
2024-12-20 00:27:33,468 - acemd - INFO - #   Surface tension: 0.0 nm bar
2024-12-20 00:27:33,468 - acemd - INFO - #   XYMode: isotropic
2024-12-20 00:27:33,468 - acemd - INFO - #   ZMode: free
2024-12-20 00:27:33,468 - acemd - INFO - #
2024-12-20 00:27:33,468 - acemd - INFO - # Non-bonded interactions
2024-12-20 00:27:33,468 - acemd - INFO - #   Cutoff distance: 9.000 A
2024-12-20 00:27:33,468 - acemd - INFO - #   Switching distance: 7.500 A
2024-12-20 00:27:33,468 - acemd - INFO - #   PME: Ewald tolerance: 0.0005
2024-12-20 00:27:33,468 - acemd - INFO - #   Reaction field dielectric: 78.5
2024-12-20 00:27:33,468 - acemd - INFO - #
2024-12-20 00:27:33,468 - acemd - INFO - # Hydrogen constraints
2024-12-20 00:27:33,468 - acemd - INFO - #   Bonds involving hydrogen are constrained
2024-12-20 00:27:33,468 - acemd - INFO - #   Making water molecules rigid
2024-12-20 00:27:33,468 - acemd - INFO - #
2024-12-20 00:27:33,469 - acemd - INFO - # No hydrogen mass repartitioning was applied
2024-12-20 00:27:42,221 - moleculekit.readers - WARNING - Non-integer values were read from the PDB "serial" field. Dropping PDB values and assigning new ones.
2024-12-20 00:27:42,605 - moleculekit.readers - WARNING - Reading PDB file with more than 99999 atoms. Bond information can be wrong.
2024-12-20 00:28:01,201 - acemd - INFO - #
2024-12-20 00:28:01,201 - acemd - INFO - # External forces
2024-12-20 00:28:08,067 - acemd - INFO - #   External force: 0
2024-12-20 00:28:08,067 - acemd - INFO - #     Type: PositionalRestraint
2024-12-20 00:28:08,067 - acemd - INFO - #     Atom selection: "((segid P1 and name C CA N O) or (not (segid P1 or lipid or water or ions) and noh) or (segid 'ION' 'WAT' and noh))"
2024-12-20 00:28:08,067 - acemd - INFO - #     Axes: xyz
2024-12-20 00:28:08,067 - acemd - INFO - #     FB width: [2.00, 2.00, 2.00] Å
2024-12-20 00:28:08,067 - acemd - INFO - #     Number of atoms: 11529
2024-12-20 00:28:08,067 - acemd - INFO - #     Setpoints
2024-12-20 00:28:08,067 - acemd - INFO - #       0         1.00 kcal/mol/Å^2 @ step 0
2024-12-20 00:28:08,067 - acemd - INFO - #       1         1.00 kcal/mol/Å^2 @ step 10000000
2024-12-20 00:28:08,067 - acemd - INFO - #       2         0.00 kcal/mol/Å^2 @ step 15000000
2024-12-20 00:28:15,121 - acemd - INFO - #
2024-12-20 00:28:15,121 - acemd - INFO - # Removing bonded terms with zero force constants
2024-12-20 00:28:15,122 - acemd - INFO - #   Harmonic bond interations
2024-12-20 00:28:15,122 - acemd - INFO - #     Initial number of terms: 796380
2024-12-20 00:28:26,272 - acemd - INFO - #     Optimized number of terms: 796380
2024-12-20 00:28:26,273 - acemd - INFO - #   Torsion interactions
2024-12-20 00:28:26,273 - acemd - INFO - #     Initial number of terms: 642942
2024-12-20 00:28:29,245 - acemd - INFO - #     Optimized number of terms: 596564
2024-12-20 00:28:37,153 - acemd.minimizer - INFO - #
2024-12-20 00:28:37,154 - acemd.minimizer - INFO - # Minimizing system with CG for 5000 steps
2024-12-20 00:28:37,154 - acemd.minimizer - INFO - #       Step      Potential   Max Force Comp.
2024-12-20 00:28:37,154 - acemd.minimizer - INFO - #                [kcal/mol]      [kcal/mol/A]
2024-12-20 00:28:37,772 - acemd.minimizer - INFO -            0 124056249614974.6406    51326090.7239
2024-12-20 00:28:37,778 - acemd.minimizer - INFO - # WARNING: due to large initial force components (51326090.72) the minimization has to switch to the CPU platform
2024-12-20 00:28:37,778 - acemd.minimizer - INFO - # Creating an auxilary platform for minimization
2024-12-20 02:08:29,709 - acemd.minimizer - INFO -            1 120730219542.1879 1574717754057.2244
2024-12-20 02:33:33,480 - acemd.minimizer - INFO -            2 2007178274.4014  7006552563.7312
2024-12-20 03:18:11,862 - acemd.minimizer - INFO -            3  59836540.7233    18281506.2799
2024-12-20 03:40:38,660 - acemd.minimizer - INFO -            4   3385174.1848     2749804.2328
2024-12-20 04:08:38,791 - acemd.minimizer - INFO -            5    338171.3547      446776.2731
2024-12-20 04:58:58,819 - acemd.minimizer - INFO -            6   -579233.0396       35614.9107
2024-12-20 04:59:06,475 - acemd.minimizer - INFO - # Switching back to the initial platform
2024-12-20 04:59:07,372 - acemd.minimizer - INFO -            7   -685177.8271      132465.4318
2024-12-20 04:59:08,096 - acemd.minimizer - INFO -            8   -832854.5603      127871.3225
2024-12-20 04:59:08,740 - acemd.minimizer - INFO -            9   -916540.8467       98301.6216
2024-12-20 04:59:09,483 - acemd.minimizer - INFO -           10  -1018299.8203      143736.7889
2024-12-20 04:59:10,133 - acemd.minimizer - INFO -           11  -1104241.9153      155997.1094
2024-12-20 04:59:10,781 - acemd.minimizer - INFO -           12  -1155765.5947      116042.1931
2024-12-20 04:59:11,525 - acemd.minimizer - INFO -           13  -1236268.7467       91229.4677
2024-12-20 04:59:12,420 - acemd.minimizer - INFO -           14  -1381124.6526      168327.7562
2024-12-20 04:59:13,234 - acemd.minimizer - INFO -           15  -1430775.5381       59921.8970
2024-12-20 04:59:13,888 - acemd.minimizer - INFO -           16  -1449542.7878       41488.6683
2024-12-20 04:59:14,544 - acemd.minimizer - INFO -           17  -1485866.9133       30404.9936
2024-12-20 04:59:15,277 - acemd.minimizer - INFO -           18  -1538881.2418       61181.0838
2024-12-20 04:59:15,934 - acemd.minimizer - INFO -           19  -1563341.9333       28672.6481
2024-12-20 04:59:16,660 - acemd.minimizer - INFO -           20  -1601209.3778       27004.0305
2024-12-20 04:59:17,467 - acemd.minimizer - INFO -           21  -1647469.4014       35863.7777
2024-12-20 04:59:18,114 - acemd.minimizer - INFO -           22  -1667599.7959       24063.7656
2024-12-20 04:59:19,069 - acemd.minimizer - INFO -           23  -1690231.3084       17952.3204
2024-12-20 04:59:19,880 - acemd.minimizer - INFO -           24  -1712156.6283        7872.4682
2024-12-20 04:59:20,612 - acemd.minimizer - INFO -           25  -1746809.2588       94804.8979
2024-12-20 04:59:21,257 - acemd.minimizer - INFO -           26  -1767233.5080       34152.2185
2024-12-20 04:59:21,984 - acemd.minimizer - INFO -           27  -1790499.1372        8271.1956
2024-12-20 04:59:22,711 - acemd.minimizer - INFO -           28  -1813835.6205       15923.9340
2024-12-20 04:59:23,518 - acemd.minimizer - INFO -           29  -1831218.9477        7779.4110
```

1) Why  # Harmonic bond interactions and skipped terms are not the same number?

``` ACEMD3
#   Harmonic bond interactions
#     Number of terms: 593050
#     Number of skipped terms: 203330

```


``` ACEMD4
#   Harmonic bond interactions
 - #   Harmonic bond interations
2024-12-20 00:28:15,122 - acemd - INFO - #     Initial number of terms: 796380
2024-12-20 00:28:26,272 - acemd - INFO - #     Optimized number of terms: 796380

```

2) Why minimization for the same system take way more longer on ACEMD4 than on ACEMD3?

**Comment by stefdoerr** [comment]
Hi, about the harmonic bond terms, I assume that I might not be removing some terms which have a force constant very close to 0 due to floating point precision errors. If you provide me the input files I can take a look. But that will not affect the simulation, don't worry about that.

As for the minimization running longer it could be because the implementation of the minimizer was moved from C++ to python in ACEMD 4, but in the tests I ran it didn't affect the minimization time since the force evaluation step was much slower than the actual minimization loop. How much slower is it in your case?

**Comment by H-EKE** [comment]
Thanks for your reply!

This is the input file that I used on ACEMD 4

```
barostat: true
barostatpressure: 1.01325
barostatconstratio: true
boxsize:
- 196.15199279785156
- 196.13400268554688
- 160.7740020751953
coordinates: structure.pdb
structure: structure.psf
extforces:
- axes: xyz
  fbwidth:
  - 2.0
  - 2.0
  - 2.0
  sel: ((segid P1 and name C CA N O) or (not (segid P1 or lipid or water or ions)
    and noh) or (segid 'ION' 'WAT' and noh))
  setpoints:
  - 1@0
  - 1@20ns
  - 0@30ns
  type: positionalRestraint
minimize: 5000
parameters: parameters
restart: false
run: 40ns
thermostat: true
thermostatdamping: 1
thermostattemperature: 310
velocities: 310
timestep: 2
trajectoryperiod: 50000
```

This was on acemd3 

```

#
barostat                on
barostatconstratio      on
barostatpressure        1.01325
boxsize                 196.15199279785156 196.13400268554688 160.7740020751953
coordinates             structure.pdb
cutoff                  9
minimize                5000
parameters              parameters
pme                     on
restart                 off
structure               structure.psf
switchdistance          7.5
switching               on
temperature             310
thermostat              on
thermostatdamping       1
thermostattemperature   310
timestep                2
trajectoryfile          output.xtc
trajectoryperiod        25000
atomRestraint           "segid P1 and name C CA N O or not (segid P1 or lipid or water or ions ) and noh or segid ION WAT and noh" axes 
xyz width "2" setpoints 1@0 1@20ns 0@30ns
run                     20000000
```



Regarding minimization, I would say it takes 3-4 hours more than before. I work mostly with membrane proteins. I have tried to do it only on opemm 8.2 but ACEMD 4 still faster

**Comment by stefdoerr** [comment]
Input I meant the whole folder (psf, parameters files and the input file) if it's not something confidential

**Comment by H-EKE** [comment]
I can share the parameters but not the structure due to confidentiality

**Comment by stefdoerr** [comment]
Don't worry then, I will try to recreate something similar

**Comment by H-EKE** [comment]
Thanks a lot!

**Comment by stefdoerr** [comment]
I checked on a system with 1 million atoms which is the largest I have and there the minimization takes equal time in ACEMD 3 and ACEMD 4 so I cannot reproduce that. I can reproduce though the not-removed harmonic bond terms, but I don't see them affecting the speed at all.

**Comment by H-EKE** [comment]
I will re-check in my side again, I may missed something. Thanks a lot @stefdoerr and sorry for the inconvenience!

**Comment by stefdoerr** [comment]
I tested on another system with 23k atoms which would be on the smaller side and again the minimization took same time between 3 and 4. So the system size does not affect the performance either. No worries, it's good for me to check anyway.
