### ISSUE TITLE
Molecule _readTopology crashes with certain protein. [Not stable/multiscalelab]

### ISSUE THREAD

**Issue by hawk31** [Acellera/htmd#112]
Not sure if it's a protein issue or a parser issue.
Small replication.
```python
In[151]: Molecule('/shared/jose/databases/pdbbind/2pyi/2pyi_protein.pdb')
Traceback (most recent call last):
  File "/home/jose/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-151-833ab03def31>", line 1, in <module>
    Molecule('/shared/jose/databases/pdbbind/2pyi/2pyi_protein.pdb')
  File "/home/jose/htmd/htmd/molecule/molecule.py", line 190, in __init__
    self.read(filename)
  File "/home/jose/htmd/htmd/molecule/molecule.py", line 698, in read
    self._readPDB(filename)
  File "/home/jose/htmd/htmd/molecule/molecule.py", line 734, in _readPDB
    self._readTopology(topo, filename)
  File "/home/jose/htmd/htmd/molecule/molecule.py", line 791, in _readTopology
    newfielddata = np.array(topo.__dict__[field], dtype=self._dtypes[field])
ValueError: could not convert string to float: 
```

**Comment by stefdoerr** [comment]
Broken PDB format on atom 12633:

```
ATOM  12632 3HG2 ILE A 805      12.362  13.214  16.810  1.00  0.00           H
ATOM  12633  CD1 ILE A 805      11.913  15.784  15.849  1.001511.00           C
ATOM  12634 1HD1 ILE A 805      11.450  15.553  14.890  1.00  0.00           H
```

Can't support broken files :/ Catch the exception and skip it

**Comment by hawk31** [comment]
Ok, then it's not a parser issue. Closing.
