### ISSUE TITLE
Molecule reading missing fields in .mae files

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#123]
Hi,

I read a maestro file in Molecule() but got the following: The molecule loads fine in vmd. File attached:
[protein.txt](https://github.com/Acellera/htmd/files/457621/protein.txt)

```
>>> mol=Molecule('protein.mae')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/acellera/test/test/python/lib/python3.5/site-packages/htmd/molecule/molecule.py", line 190, in __init__
    self.read(filename)
  File "/path/to/acellera/test/test/python/lib/python3.5/site-packages/htmd/molecule/molecule.py", line 728, in read
    topo, coords = MAEread(filename)
  File "/path/to/acellera/test/test/python/lib/python3.5/site-packages/htmd/molecule/readers.py", line 340, in MAEread
    .format(fname, len(section_dict), len(row)))
RuntimeError: protein.mae has 44 fields in the m_atom section description, but 44 fields in the section data. Please check for missing fields in the mae file.
```

**Comment by stefdoerr** [comment]
I fixed it https://github.com/Acellera/htmd/commit/97abee2980e1687280b374bf0decab3763249151 but I think I probably broke other MAE files. The issue is that some MAE files assume by default that the first column will be the indexes and don't describe it in the m_atom section (which they should). Yours does so it failed with this ridiculous error because I was used to reading the other kind.
But I'm afraid now it will fail on other MAE files. We will see in the future.
