### ISSUE TITLE
Issue with PDBread after pandas update

### ISSUE THREAD

**Issue by hawk31** [Acellera/htmd#125]
Replication 

```python
In[376]: pocket = '/shared/jose/databases/asbench/AsBench_Core_Set/allosteric_proteins/AS057013401_4KH1_out/pockets/pocket0_atm.pdb'
In[377]: Molecule(pocket)
/home/jose/anaconda3/lib/python3.5/site-packages/pandas/core/ops.py:716: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(x, name)(y)
Traceback (most recent call last):
  File "/home/jose/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-373-6170f984cd69>", line 1, in <module>
    Molecule(pocket)
  File "/home/jose/htmd/htmd/molecule/molecule.py", line 190, in __init__
    self.read(filename)
  File "/home/jose/htmd/htmd/molecule/molecule.py", line 698, in read
    self._readPDB(filename)
  File "/home/jose/htmd/htmd/molecule/molecule.py", line 733, in _readPDB
    topo, coords = PDBread(filename, mode=mode)
  File "/home/jose/htmd/htmd/molecule/readers.py", line 592, in PDBread
    parsedtopo.loc[parsedtopo.chargesign == '-', 'charge'] *= -1
  File "/home/jose/anaconda3/lib/python3.5/site-packages/pandas/core/ops.py", line 763, in wrapper
    res = na_op(values, other)
  File "/home/jose/anaconda3/lib/python3.5/site-packages/pandas/core/ops.py", line 718, in na_op
    raise TypeError("invalid type comparison")
TypeError: invalid type comparison
```

**Comment by stefdoerr** [comment]
Happens when people right-align their charges in the PDB format. I will take a look if I can make the parser more flexible with the charges.

**Comment by stefdoerr** [comment]
Fixed: https://github.com/Acellera/htmd/commit/e7ce599c4b627cf36191c8988c4d0f3ebb749f12

**Comment by hawk31** [comment]
Do not hate me. It's the .pdbqt parser this time.

```python
In [3]: ligand = '/shared/jose/databases/asbench/AsBench_Core_Set/allosteric_modulators/AS003019101_1PCQ_ligand.pdbqt'

In [4]: Molecule(ligand)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-f9bc3c0b9e81> in <module>()
----> 1 Molecule(ligand)

/home/jose/anaconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py in __init__(self, filename, name)
    188 
    189         if filename:
--> 190             self.read(filename)
    191             if isinstance(filename, str):
    192                 self.topoloc = os.path.abspath(filename)

/home/jose/anaconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py in read(self, filename, type, skip, frames, append)
    698             self._readPDB(filename)
    699         elif (type is None and firstfile.endswith(".pdbqt")) or type == "pdbqt":
--> 700             self._readPDB(filename, mode='pdbqt')
    701         elif (type is None and firstfile.endswith(".xtc")) or type == "xtc":
    702             self._readTraj(filename, skip=skip, frames=frames, append=append)

/home/jose/anaconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py in _readPDB(self, filename, mode)
    732         if os.path.isfile(filename):
    733             topo, coords = PDBread(filename, mode=mode)
--> 734             self._readTopology(topo, filename)
    735             self.coords = np.atleast_3d(np.array(coords, dtype=self._dtypes['coords']))
    736         elif len(filename) == 4:

/home/jose/anaconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py in _readTopology(self, topo, filename, overwrite)
    832 
    833         for field in topo.__dict__:
--> 834             newfielddata = np.array(topo.__dict__[field], dtype=self._dtypes[field])
    835             if len(newfielddata) == 0:
    836                 continue

ValueError: invalid literal for int() with base 10: '_602'

```

**Comment by stefdoerr** [comment]
```
ATOM     43  H8  ADP A 600      26.821 -38.751 -16.841  0.00  0.00     0.144 H 
ATOM     28 AL   AF3 A_602      34.566 -43.237 -20.123  0.00  0.00     0.000 Al
```
Underscores in the resid columns.
[Undocumented](http://autodock.scripps.edu/faqs-help/faq/what-is-the-format-of-a-pdbqt-file) = Unsupported :stuck_out_tongue:
