### ISSUE TITLE
Newparameterize fails

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#133]
Hi, 

I have test newparameterize in the set of compounds.
I run `newparameterize -m input.mol2`

21/23 failed with this error: 
```
Traceback (most recent call last):
  File "/path/to/acellera/test/python/bin/newparameterize", line 6, in <module>
    sys.exit(htmd.newparameterization.cli.main_parameterize())
  File "/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/newparameterization/cli.py", line 113, in main_parameterize
    (score, qm_dipole, mm_dipole) = mol.fitCharges()
  File "/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/newparameterization/ffmolecule.py", line 247, in fitCharges
    raise RuntimeError("QM Calculation failed")
RuntimeError: QM Calculation failed
```
The other two failed as:

```
Traceback (most recent call last):
  File "/path/to/acellera/test/python/bin/newparameterize", line 6, in <module>
    sys.exit(htmd.newparameterization.cli.main_parameterize())
  File "/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/newparameterization/cli.py", line 150, in main_parameterize
    printEnergies( mol )
  File "/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/newparameterization/cli.py", line 21, in printEnergies
    ffe = FFEvaluate( mol )
  File "/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/newparameterization/ffevaluate.py", line 35, in __init__
    dd = self.prm.dihedralParam( self.rtf.type_by_index[d[0]], self.rtf.type_by_index[d[1]], self.rtf.type_by_index[d[2]], self.rtf.type_by_index[d[3]] )
  File "/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/newparameterization/ff.py", line 323, in dihedralParam
    raise ValueError( "Could not find dihedral parameters for %s-%s-%s-%s" %( n1, n2, n3, n4 ) )
ValueError: Could not find dihedral parameters for O301-CRC1-CRC1-O301
```

Let me know any ideas
Thanks,
Noelia

**Comment by mj-harvey** [comment]
Hi Noelia,

For the QM failures: Are you using gaussian or psi4 for the qm? IF gaussian, try with psi4, that's what all our testing's done with
 
For the other two: Could you mail me the problematic mol2s, please? I haven't seen that error. For some reason the ff doesn't contain params for that dihedral. Does it also happen  with the old parameterise?

**Comment by mj-harvey** [comment]
Also -- please ensure that the psi4 package version is 1.0.54 and update if not. You may have to explicitly remove any old version which likely had a higher version number.

**Comment by noeliaferruz** [comment]
Hi, 

I am using gaussian, I haven't found a way to specify psi4 in the command line. Psi4 is installed in version 1.0.54 in any case.
```
You are on the latest HTMD version (1.3.10).
usage: newparameterize [-h] [-m MOL] [-c CHARGE] [--rtf RTF] [--prm PRM]
                       [-o DIRECTORY] [-l] [-t A1-A2-A3-A4] [-n NCPUS]
                       [-f {GAFF,GAFF2,CGENFF}] [-b {6-31g-star,cc-pVTZ}]

Acellera Small Molecule Parameterisation Version 2.0

optional arguments:
  -h, --help            show this help message and exit
  -m MOL, --mol2 MOL    Molecule to parameterise, in mol2 format
  -c CHARGE, --charge CHARGE
                        Net charge on molecule
  --rtf RTF             Inital RTF parameters (req --prm)
  --prm PRM             Inital PRM parameters (req --rtf)
  -o DIRECTORY, --output DIRECTORY
                        Output directory
  -l, --list            List parameterisable torsions
  -t A1-A2-A3-A4, --torsion A1-A2-A3-A4
                        Torsion to parameterise (default all)
  -n NCPUS, --ncpus NCPUS
                        Number of CPUs to use (default 8)
  -f {GAFF,GAFF2,CGENFF}, --forcefield {GAFF,GAFF2,CGENFF}
                        Inital FF guess to use
  -b {6-31g-star,cc-pVTZ}, --basis {6-31g-star,cc-pVTZ}
                        QM Basis Set
```
Let's first focus on one compound with just one dihedral first -attached-. The error was:
```
 == Diagnostic Energies ==
Traceback (most recent call last):
  File "/path/to/acellera/test/python/bin/newparameterize", line 6, in <module>
    sys.exit(htmd.newparameterization.cli.main_parameterize())
  File "/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/newparameterization/cli.py", line 150, in main_parameterize
    printEnergies( mol )
  File "/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/newparameterization/cli.py", line 21, in printEnergies
    ffe = FFEvaluate( mol )
  File "/path/to/acellera/test/python/lib/python3.5/site-packages/htmd/newparameterization/ffevaluate.py", line 20, in __init__
    self.mol.charge[i] = self.rtf.charge_by_name[ self.mol.name[i] ]
KeyError: 'C*1'
```
[input.txt](https://github.com/Acellera/htmd/files/483631/input.txt)

Let me know how to run in psi4. The preferred software here is gaussian though.
 
Thanks,
Noelia

**Comment by mj-harvey** [comment]
It's the asterisk in the atom names.  Remove them, along with any directories produced by the last failed attempt (minimize/ esp/ dihedral-opt/) and try again.

I asked Joao to get the PSI4 updated - that may have happened before you checked. Please remove the "esp" directory and try again. This version of parameterise will actually always use PSI4.

**Comment by mj-harvey** [comment]
fixed in c49a453a1ae7acbccfd27813b0668ecde48d10ad

**Comment by j3mdamas** [comment]
Hi matt,
We checked the computer where it was running, and it was running gaussian.
Tomorrow I'll try to do more checks.

**Comment by mj-harvey** [comment]
Yea, my mistake. It has the same logic as the old one -- Guassian takes priority over PSI4. 
I haven't tested with Gaussian at all, please use PSI4. In practice this means g09/g03 shouldn't be in the PATH.

**Comment by noeliaferruz** [comment]
Ok, it's running again

**Comment by mj-harvey** [comment]
@noeliaferruz  I'd still like to see the structure that yielded:

ValueError: Could not find dihedral parameters for O301-CRC1-CRC1-O301

**Comment by mj-harvey** [comment]
Joao tells me it can't be reproduced with the current code, so let's close the issue. Open a new one if it recurs.
