### ISSUE TITLE
--charge flag does not work

### ISSUE THREAD

**Issue by GerardBCN** [Acellera/htmd#142]
```
Traceback (most recent call last):
  File "/shared/gerard/anaconda3/bin/newparameterize", line 6, in <module>
    sys.exit(htmd.newparameterization.cli.main_parameterize())
  File "/shared/gerard/anaconda3/lib/python3.5/site-packages/htmd/newparameterization/cli.py", line 120, in main_parameterize
    mol = FFMolecule(filename=filename, method=method, netcharge=args.charge, rtf=args.rtf, prm=args.prm, basis=basis, execution=execution, qmcode=code )
  File "/shared/gerard/anaconda3/lib/python3.5/site-packages/htmd/newparameterization/ffmolecule.py", line 69, in __init__
    self.netcharge = int(round(charge))
NameError: name 'charge' is not defined
```
@j3mdamas

**Comment by j3mdamas** [comment]
fixed 36dc52c1ae61788d5ef140cba8f25a2197c28e46
