### ISSUE TITLE
Build example on the HTMD website doesn't work

### ISSUE THREAD

**Issue by mj-harvey** [Acellera/htmd#207]
```
from htmd import *
m = Molecule('2HBA')
m.filter('(protein and chain A) or waters within 5 of (protein and chain A)')
pm = proteinPrepare(m)      # protonation, side chain optimization
pm = autoSegment(pm)        # set protein segments
pmsol = solvate(pm, pad=12) # solvate
bm = charmm.build(pmsol, outdir='./build', saltconc=0.15) # build topology
```

```
$ python --version
Python 3.5.2 :: Continuum Analytics, Inc.
-bash-4.2$ python3 build.py 

Please cite -- HTMD: High-Throughput Molecular Dynamics for Molecular Discovery
J. Chem. Theory Comput., 2016, 12 (4), pp 1845-1852. 
http://pubs.acs.org/doi/abs/10.1021/acs.jctc.6b00049

You are on the latest HTMD version (1.5.4).

2016-12-14 17:41:17,676 - htmd.molecule.molecule - INFO - Attempting PDB query for 2HBA
2016-12-14 17:41:18,334 - htmd.molecule.molecule - INFO - Removed 468 atoms. 462 atoms remaining in the molecule.
2016-12-14 17:41:18,383 - propka - INFO - No pdbfile provided
Traceback (most recent call last):
  File "build.py", line 5, in <module>
    pm = proteinPrepare(m)      # protonation, side chain optimization
  File "/home/mjharvey/miniconda3/lib/python3.5/site-packages/htmd/builder/preparation.py", line 268, in proteinPrepare
    holdList=hlist)
ValueError: too many values to unpack (expected 4)
´´´


1) What is wrong?

2) Why isn't this one of the CI tests?

**Comment by j3mdamas** [comment]
the problem is with proteinPrepare. Toni is making lots of changes. @tonigi, I updated htmd-pdb2pqr and it's still giving the same error as it's giving to Matt

```
In [5]: pm = proteinPrepare(m)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-c6f13288c56a> in <module>()
----> 1 pm = proteinPrepare(m)

/home/joao/miniconda3/lib/python3.5/site-packages/htmd/builder/preparation.py in proteinPrepare(mol_in, pH, verbose, returnDetails, hydrophobicThickness, holdSelection)
    266                                                              ph_calc_method="propka31",
    267                                                              ph_calc_options=propka_opts,
--> 268                                                              holdList=hlist)
    269     tmpin.close()
    270 

ValueError: too many values to unpack (expected 4)
```

**Comment by mj-harvey** [comment]
Any example that appears on the web page *must* also be a travis test so, at the very least!, we have warning to keep them up to date. This is with a release, not the HEAD, so it shouldn't happen. Right now HTMD's going to fail any new user at the first hurdle.

**Comment by j3mdamas** [comment]
Update htmd to 1.5.5. It works there.

**Comment by mj-harvey** [comment]
Ok, seems conda had lost my channels settings, so it was lying when it claimed it had the latest release.

**Comment by j3mdamas** [comment]
1.5.4 is not compatible with the latest htmd-pdb2pqr

**Comment by tonigi** [comment]
It is an unfortunate version dependency, sorry, but I needed to change the
internal API for the "repreparation" (change protonation) function.



Il 14 dic 2016 6:54 PM, "João M. Damas" <notifications@github.com> ha
scritto:
