### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by GerardBCN** [Acellera/htmd#214]
```
Iteration 2
 Fitting converged at iteration 2
Traceback (most recent call last):
  File "/shared/gerard/anaconda3/bin/parameterize", line 6, in <module>
    sys.exit(htmd.parameterization.cli.main_parameterize())
  File "/shared/gerard/HTMD/htmd/htmd/parameterization/cli.py", line 272, in main_parameterize
    fit = mol.plotConformerEnergies(rets, show=False)
  File "/shared/gerard/HTMD/htmd/htmd/parameterization/ffmolecule.py", line 777, in plotConformerEnergies
    qm_energy = qm_energy - min(qm_energy)
```
Parameterization folder @ pub.htmd.org/0_21_12_2016.zip

**Comment by mj-harvey** [comment]
Bug occurs when molecule doesn't have any soft torsions. Fixed in HEAD
