### ISSUE TITLE
OSError: /htmd/lib/Linux/libvmdparser.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by GerardBCN** [Acellera/htmd#217]
On importing htmd:

```
>>> from htmd import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/shared/gerard/HTMD/htmd/htmd/__init__.py", line 9, in <module>
    from htmd.simlist import simlist, simfilter, simmerge
  File "/shared/gerard/HTMD/htmd/htmd/simlist.py", line 17, in <module>
    from htmd.molecule.molecule import Molecule
  File "/shared/gerard/HTMD/htmd/htmd/molecule/molecule.py", line 11, in <module>
    from htmd.molecule.vmdparser import guessbonds, vmdselection
  File "/shared/gerard/HTMD/htmd/htmd/molecule/vmdparser.py", line 21, in <module>
    parser = ct.cdll.LoadLibrary(os.path.join(libdir, "libvmdparser.so"))
  File "/shared/gerard/anaconda3/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/shared/gerard/anaconda3/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /shared/gerard/HTMD/htmd/htmd/lib/Linux/libvmdparser.so: cannot open shared object file: No such file or directory
```

**Comment by GerardBCN** [comment]
using head

**Comment by GerardBCN** [comment]
seems that got deleted in the last pull:

` htmd/lib/Linux/libvmdparser.so                       |  Bin 3328429 -> 0 bytes`

**Comment by mj-harvey** [comment]
GerardBCN - consequence of recent changes to the structure of the repo. Please pull to fix.
