### ISSUE TITLE
liblicense issue

### ISSUE THREAD

**Issue by mj-harvey** [Acellera/htmd#221]
Configuring...
Traceback (most recent call last):
  File "/home/scott/miniconda3/bin/acecloud", line 6, in <module>
    sys.exit(acecloud.client.main_acecloud())
  File "./client.py", line 70, in main_acecloud
  File "./client.py", line 279, in setup
  File "./cloud.py", line 26, in __init__
  File "/home/scott/miniconda3/lib/python3.5/site-packages/htmd/license.py", line 24, in licenseEntitlements
    lib = cdll.LoadLibrary(os.path.join(libdir, "liblicense.so"))
  File "/home/scott/miniconda3/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/home/scott/miniconda3/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/scott/miniconda3/lib/python3.5/site-packages/htmd/lib/Linux/liblicense.so: undefined symbol: BIO_vfree

**Comment by mj-harvey** [comment]
Fixed in 1.5.9
