### ISSUE TITLE
Can't run parameterize: ImportError: bad magic number in 'acecloud': b'\x17\r\r\n'

### ISSUE THREAD

**Issue by GerardBCN** [Acellera/htmd#261]
The error I get:
```
Please cite HTMD: Doerr et al.(2016)JCTC,12,1845. https://dx.doi.org/10.1021/acs.jctc.6b00049

HTMD Documentation at: https://www.htmd.org/docs/latest/

You are on the latest HTMD version (1.7.0).

Traceback (most recent call last):
  File "/shared/gerard/anaconda3/bin/parameterize", line 6, in <module>
    sys.exit(htmd.parameterization.cli.main_parameterize())
  File "/shared/gerard/anaconda3/lib/python3.5/site-packages/htmd/parameterization/cli.py", line 64, in main_parameterize
    from htmd.parameterization.ffmolecule import FFMolecule, FFEvaluate
  File "/shared/gerard/anaconda3/lib/python3.5/site-packages/htmd/parameterization/ffmolecule.py", line 13, in <module>
    from htmd.qm.qmcalculation import Theory, BasisSet, Code, QMCalculation, Execution
  File "/shared/gerard/anaconda3/lib/python3.5/site-packages/htmd/qm/qmcalculation.py", line 24, in <module>
    from htmd.queues.acecloudqueue import AceCloudQueue
  File "/shared/gerard/anaconda3/lib/python3.5/site-packages/htmd/queues/acecloudqueue.py", line 13, in <module>
    from acecloud.cloud import Cloud
ImportError: bad magic number in 'acecloud': b'\x17\r\r\n'

```

**Comment by j3mdamas** [comment]
Works on miniconda3. I'm going to install through anaconda3, to see if I can reproduce.

**Comment by j3mdamas** [comment]
Just did a fresh anaconda3 install and I have no problems.

You know what they say... Just do a fresh conda installation and it should solve the problem

**Comment by GerardBCN** [comment]
I solved it by installing anaconda3 from continuum repo, conda install python=3.5 -y and then conda install htmd -c acellera
