### ISSUE TITLE
Protocolinferface

### ISSUE THREAD

**Issue by PabloHNieto** [Acellera/htmd#271]
Hi,
since yesterday my adaptive runs are crashing with the following message

```
Traceback (most recent call last):
  File "p53_adaptive.py", line 26, in <module>
    md.projection= [MetricDihedral(protsel="protein", sincos=True)]
  File "/shared/pablo/miniconda3/lib/python3.5/site-packages/protocolinterface/protocolinterface.py", line 41, in __setattr__
    self._validate(key, value)
  File "/shared/pablo/miniconda3/lib/python3.5/site-packages/protocolinterface/protocolinterface.py", line 112, in _validate
    raise TypeError('Failed to set attribute "{}" because {}'.format(key, e))
TypeError: Failed to set attribute "projection" because it does not accept lists.
```
I'm setting my projection as follows (with one or several metrics), which used to work 
`md.projection= [MetricDihedral(protsel="protein", sincos=True)]`

Pablo

**Comment by stefdoerr** [comment]
Fixed
