### ISSUE TITLE
error during adaptive sampling

### ISSUE THREAD

**Issue by funnybomb** [Acellera/htmd#287]
hi, I am using adaptive samplie by 
```python
# set up
from htmd import *
from htmd.protocols.production_v4 import Production

md = Production()
md.runtime = 10
md.timeunits = 'ns'
md.temperature  = 300
md.acemd.bincoordinates = 'output.coor'
md.acemd.extendedsystem  = 'output.xsc'
md.acemd.binvelocities = None
md.write('equil','prod_adaptive')

## run
md = AdaptiveMD()
md.nmin=3
md.nmax=5
md.nepochs = 80
md.app = AcemdLocal(datadir='./data/')
#md.app = AcemdLocal()
md.generatorspath='./prod_adaptive'
#md.datapath = './data/'
md.projection=[MetricDihedral()]
md.ticadim = 3
md.updateperiod = 7200 # execute every 2 hours
md.run()

```
I got exit and the log file is 
```
2017-03-21 18:37:01,386 - htmd.molecule.readers - WARNING - Non-integer values were read from the PDB "serial" field. Dropping PDB values and assigning new ones.
2017-03-21 18:37:01,389 - htmd.molecule.readers - WARNING - Non-integer values were read from the PDB "serial" field. Dropping PDB values and assigning new ones.
2017-03-21 18:37:04,083 - htmd.molecule.readers - WARNING - Reading PDB file with more than 99999 atoms. Bond information can be wrong.
2017-03-21 18:37:04,087 - htmd.molecule.readers - WARNING - Reading PDB file with more than 99999 atoms. Bond information can be wrong.

2017-03-21 18:37:37,733 - htmd.projections.metric - INFO - Frame step 0.1ns was read from the trajectories. If it looks wrong, redefine it by manually setting the MetricData.fstep property.
2017-03-21 18:37:37,733 - htmd.metricdata - INFO - Dropped 0 trajectories from 2 resulting in 2
2017-03-21 18:39:03,815 - htmd.metricdata - INFO - Dropped 0 trajectories from 2 resulting in 2
```
```pytb
/home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/dense/decomposition.py:545: SpectralWarning: Multiple eigenvalues with magnitude one.
  warnings.warn('Multiple eigenvalues with magnitude one.', SpectralWarning)


Traceback (most recent call last):
  File "/home/funnybomb/anaconda3/lib/python3.5/site-packages/pyemma/msm/models/msm.py", line 910, in pcca
    if self._pcca.n_metastable != m:
AttributeError: 'MaximumLikelihoodMSM' object has no attribute '_pcca'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_adaptive.py", line 14, in <module>
    md.run()
  File "/home/funnybomb/anaconda3/lib/python3.5/site-packages/htmd/adaptive/adaptive.py", line 99, in run
    flag = self._algorithm()
  File "/home/funnybomb/anaconda3/lib/python3.5/site-packages/htmd/adaptive/adaptiverun.py", line 127, in _algorithm
    self._createMSM(data)
  File "/home/funnybomb/anaconda3/lib/python3.5/site-packages/htmd/adaptive/adaptiverun.py", line 170, in _createMSM
    self._model.markovModel(self.lag, self._numMacrostates(data))
  File "/home/funnybomb/anaconda3/lib/python3.5/site-packages/htmd/model.py", line 86, in markovModel
    self.coarsemsm = self.msm.pcca(macronum)
  File "/home/funnybomb/anaconda3/lib/python3.5/site-packages/pyemma/msm/models/msm.py", line 915, in pcca
    self._pcca = PCCA(self.transition_matrix, m)
  File "/home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/api.py", line 1450, in _pcca_object
    return dense.pcca.PCCA(T, m)
  File "/home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/dense/pcca.py", line 535, in __init__
    self._M = pcca(P, m)
  File "/home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/dense/pcca.py", line 430, in pcca
    chi[component, ipcca:ipcca + m_by_component] = _pcca_connected(closed_components_Psub[i], m_by_component)
  File "/home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/dense/pcca.py", line 299, in _pcca_connected
    (chi, rot_matrix) = _pcca_connected_isa(evecs, n)
  File "/home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/dense/pcca.py", line 83, in _pcca_connected_isa
    assert diffs[1] > 1e-6, "An eigenvector after the first one is constant. " \
AssertionError: An eigenvector after the first one is constant. Probably the eigenvectors are incorrectly sorted. Cannot do PCCA.
```

**Comment by stefdoerr** [comment]
Hmm I've never seen that before. It's coming from PyEMMA but I can't tell what the reason is. Possibly lack of data. I will just summon @marscher who might know something more.

To help them debug this, try doing `%debug` when it crashes in an ipython console or jupyter, go up the stack until you hit the `self._M = pcca(P, m)` line and save the `P` variable into a numpy `npy` file.

**Comment by j3mdamas** [comment]
@funnybomb, can you also tell us which versions are you using?

```
conda list | egrep acellera
```

Thanks

**Comment by marscher** [comment]
The transition matrix would be indeed helpful 👍

**Comment by funnybomb** [comment]
previously, there was no problem when I used htmd 1.5.xx version just after the metricdihedral problem was fixed.

conda list | egrep acellera

```
acecloud-client           1.0.35                   py35_1    acellera
acemd                     2016.10.27                    0    acellera
acemd-examples            2016.5.12                     1    acellera
ambermini                 16.16.0                       5    acellera
bhmm                      0.6.1               np111py35_0    acellera
dftd3                     3.2.0                         7    acellera
funcsigs                  1.0.0                      py_1    acellera
htmd                      1.7.13                   py35_0    acellera
htmd-data                 0.0.45                     py_0    acellera
htmd-deps                 1.7.13                   py35_0    acellera
htmd-pdb2pqr              2.1.2+htmd3                py_0    acellera
match                     0.0.3                         0    acellera
mdtraj                    1.8.0               np111py35_0    acellera
msmtools                  1.2                 np111py35_0    acellera
nglview                   0.6.2.2                  py35_0    acellera
openbabel                 2015.09                  py35_1    acellera
pcmsolver                 1.1.4                         0    acellera
pint                      0.7.2                    py35_0    acellera
plumed1                   1.3.2                         0    acellera
plumed2                   2.3.0                         0    acellera
progress_reporter         1.3.1                    py35_0    acellera
propka                    3.1.6                    py35_0    acellera
protocolinterface         0.1.3                      py_0    acellera
psfgen                    1.6.9                         0    acellera
psi4                      1.0.54                   py35_9    acellera
pyemma                    2.3.2               np111py35_1    acellera
thermotools               0.2.5               np111py35_0    acellera
vina                      1.1.101                       0    acellera
```

**Comment by j3mdamas** [comment]
Thanks for the versions.

Can you follow @stefdoerr's suggestion?

Run your script inside ipython (using `%run <name-of-script>.py`) or, if a .ipynb, execute it through jupyter.

In any case, run `%debug` after the error (in a separate cell, in case of jupyter). Type `up` and press `Enter` until you reach the `self._M = pcca(P, m)` frame (three types, I believe). Then, do: `print(m)`, and tell us the output, and run `np.save('P.npy', P)` and send us the `P.npy` file.

Thank you,
João

**Comment by funnybomb** [comment]
the log is below:
```
2017-03-27 06:14:43,662 - conda.base.context - INFO - No cio_test package found.

Please cite HTMD: Doerr et al.(2016)JCTC,12,1845. https://dx.doi.org/10.1021/acs.jctc.6b00049

HTMD Documentation at: https://www.htmd.org/docs/latest/

Using Anaconda API: https://api.anaconda.org
New devel HTMD version (1.7.14 python[==3.5,==3.6]) is available. You are currently on (1.7.13). Use 'conda update -c acellera htmd' to update to the new version. You might need to update your python version as well if there is no release for your current version.

/home/funnybomb/MD/reanalysis/3rbz_run/adaptive/run_adaptive.py:7: DeprecationWarning: The `AcemdLocal` class has been deprecated since version 1.5.15. Use `htmd.queues.localqueue.LocalGPUQueue` instead.
  md.app = AcemdLocal(datadir='./data/')
```
and I did what you told @j3mdamas , below is the result
```
> /home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/dense/pcca.py(83)_pcca_connected_isa()
     81     assert diffs[0] < 1e-6, "First eigenvector is not constant. This indicates that the transition matrix " \
     82                             "is not connected or the eigenvectors are incorrectly sorted. Cannot do PCCA."
---> 83     assert diffs[1] > 1e-6, "An eigenvector after the first one is constant. " \
     84                             "Probably the eigenvectors are incorrectly sorted. Cannot do PCCA."
     85 

ipdb> 
ipdb> up
> /home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/dense/pcca.py(299)_pcca_connected()
    297 
    298     # create initial solution using PCCA+. This could have negative memberships
--> 299     (chi, rot_matrix) = _pcca_connected_isa(evecs, n)
    300 
    301     #print "initial chi = \n",chi

ipdb> up
> /home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/dense/pcca.py(430)pcca()
    428         elif (m_by_component > 1):
    429             #print "submatrix: ",closed_components_Psub[i]
--> 430             chi[component, ipcca:ipcca + m_by_component] = _pcca_connected(closed_components_Psub[i], m_by_component)
    431             ipcca += m_by_component
    432         else:

ipdb> up
> /home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/dense/pcca.py(535)__init__()
    533         # PCCA memberships
    534         # TODO: can be improved. pcca computes stationary distribution internally, we don't need to compute it twice.
--> 535         self._M = pcca(P, m)
    536 
    537         # stationary distribution

ipdb> up
> /home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/api.py(1450)_pcca_object()
   1448         T = T.toarray()
   1449     T = _types.ensure_ndarray(T, ndim=2, uniform=True, kind='numeric')
-> 1450     return dense.pcca.PCCA(T, m)
   1451 
   1452 
```

**Comment by funnybomb** [comment]
```
np.save('P.npy', P)
```
is keeping on running for more than 2 hours ...
I will upload the result once finished

**Comment by j3mdamas** [comment]
I think you went up one more, maybe? What is the value of `m` in your case?

**Comment by funnybomb** [comment]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-cb5aefb55a12> in <module>()
----> 1 np.save('P.npy', P)

NameError: name 'P' is not defined

**Comment by j3mdamas** [comment]
So maybe you were in the right debug frame in the initial trial. Stefan, do
you know why it could take so long to write the matrix?

**Comment by stefdoerr** [comment]
No, P should have the KxK dimensions where K number of clusters which should max out at around 1200. So it should write fast.

**Comment by j3mdamas** [comment]
OK, let's see. Could you please do the initial procedure where you said it
was taking 2 hours to finish, but before using the np.save, do
print(P.shape). Thanks.

**Comment by funnybomb** [comment]
I'll remove the directory and reproduce the result, I will put result tomorrow

**Comment by funnybomb** [comment]
```
np.save('m.npy', m)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-3c7e639a293a> in <module>()
----> 1 np.save('m.npy', m)

NameError: name 'm' is not defined
```

**Comment by j3mdamas** [comment]
At which frame are you? There is no `m` at that debug frame. Is `P` available?

Do this you did here: https://github.com/Acellera/htmd/issues/287#issuecomment-289325197

At that point, with that amount of ups, you should have `P` and `m` available.

`P` should be a numpy array. Do the `print(P.shape)` and the `np.save('P.npy', P)` there.
`m` should be an int, so you just need to do `print(m)`

Thanks,
João

**Comment by funnybomb** [comment]
this is the out put of ```%run run_adaptive.py
```python
2017-03-31 00:10:17,225 - htmd.apps.localqueue - INFO - Moving simulation /home/funnybomb/MD/reanalysis/3rbz_run/adaptive/input/e1s5_prod_adaptive/output.xtc to ./data/e1s5_prod_adaptive.
2017-03-31 00:10:17,226 - htmd.apps.localqueue - INFO - Completed /home/funnybomb/MD/reanalysis/3rbz_run/adaptive/input/e1s5_prod_adaptive
2017-03-31 00:10:17,226 - htmd.apps.localqueue - INFO - Running /home/funnybomb/MD/reanalysis/3rbz_run/adaptive/input/e2s1_e1s2p0f69 on GPU device 0
2017-03-31 05:04:13,261 - htmd.apps.localqueue - INFO - Moving simulation /home/funnybomb/MD/reanalysis/3rbz_run/adaptive/input/e2s1_e1s2p0f69/output.xtc to ./data/e2s1_e1s2p0f69.
2017-03-31 05:04:13,262 - htmd.apps.localqueue - INFO - Completed /home/funnybomb/MD/reanalysis/3rbz_run/adaptive/input/e2s1_e1s2p0f69
2017-03-31 05:04:13,262 - htmd.apps.localqueue - INFO - Running /home/funnybomb/MD/reanalysis/3rbz_run/adaptive/input/e2s2_e1s2p0f71 on GPU device 0
2017-03-31 09:58:06,602 - htmd.apps.localqueue - INFO - Moving simulation /home/funnybomb/MD/reanalysis/3rbz_run/adaptive/input/e2s2_e1s2p0f71/output.xtc to ./data/e2s2_e1s2p0f71.
2017-03-31 09:58:06,603 - htmd.apps.localqueue - INFO - Completed /home/funnybomb/MD/reanalysis/3rbz_run/adaptive/input/e2s2_e1s2p0f71
```
and I repeat the ```%debug```  and four 'up', I got this result below,
```
> /home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/dense/pcca.py(83)_pcca_connected_isa()
     81     assert diffs[0] < 1e-6, "First eigenvector is not constant. This indicates that the transition matrix " \
     82                             "is not connected or the eigenvectors are incorrectly sorted. Cannot do PCCA."
---> 83     assert diffs[1] > 1e-6, "An eigenvector after the first one is constant. " \
     84                             "Probably the eigenvectors are incorrectly sorted. Cannot do PCCA."
     85 

ipdb> up
> /home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/dense/pcca.py(299)_pcca_connected()
    297 
    298     # create initial solution using PCCA+. This could have negative memberships
--> 299     (chi, rot_matrix) = _pcca_connected_isa(evecs, n)
    300 
    301     #print "initial chi = \n",chi

ipdb> up
> /home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/dense/pcca.py(430)pcca()
    428         elif (m_by_component > 1):
    429             #print "submatrix: ",closed_components_Psub[i]
--> 430             chi[component, ipcca:ipcca + m_by_component] = _pcca_connected(closed_components_Psub[i], m_by_component)
    431             ipcca += m_by_component
    432         else:

ipdb> up
> /home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/dense/pcca.py(535)__init__()
    533         # PCCA memberships
    534         # TODO: can be improved. pcca computes stationary distribution internally, we don't need to compute it twice.
--> 535         self._M = pcca(P, m)
    536 
    537         # stationary distribution

ipdb> up
> /home/funnybomb/anaconda3/lib/python3.5/site-packages/msmtools/analysis/api.py(1450)_pcca_object()
   1448         T = T.toarray()
   1449     T = _types.ensure_ndarray(T, ndim=2, uniform=True, kind='numeric')
-> 1450     return dense.pcca.PCCA(T, m)
   1451 
   1452 

ipdb> q
```

and I still got 
```
NameError: name 'm' is not defined
NameError: name 'P' is not defined
```

**Comment by j3mdamas** [comment]
It's just three `up`s. And do the `print(P.shape)`, `np.save('P.npy', P)`, and `print(m)` while still inside debug mode (before hitting `q`)

**Comment by funnybomb** [comment]
curious that I upgrade htmd to newest version, clean the data and rerun the script, there is nothing wrong for more than 2 days.

**Comment by j3mdamas** [comment]
great, good news then. I'm going to close this issue then.

sorry for bothering you, @marscher
