### ISSUE TITLE
Parameterize: parameter fits look perfect but simulations blow up because of high VDW energy

### ISSUE THREAD

**Issue by GerardBCN** [Acellera/htmd#295]
Hi, I have the following [ligand](http://www.chemspider.com/ImagesHandler.ashx?id=20066751&w=250&h=250) and I parameterized it using parameterize. The fit plots have never looked as good as these ones, just an example:

![c4-c5-c6-c7](https://cloud.githubusercontent.com/assets/3877758/24617255/b3131968-1893-11e7-8943-a83c5bfce940.png)

(full data in the .zip)

However, after building the systems, simulations blow up in he first steps of the equilibration, presumably because of super high VDW energy:

```
#     Step	      Bond	     Angle	     Dihed	      Elec	       VDW	        PE	        KE	  External	     Total	      Temp	      Pres	   PresAve
         0	   34.6587	  125.8797	   22.3547	-26967.1994	9671647875301380.0000	9671647875274594.0000	 4548.3250	    0.0000	9671647875279142.0000	  301.2796	79553753685936620035350777036800.0000	79553753685936620035350777036800.0000
# Simulation unstable. Flag 0 value 172
# The simulation has become unstable. Terminating to avoid lock-up
```
Params:
[params.zip](https://github.com/Acellera/htmd/files/890591/params.zip)

Equilibration folder:
[equil.zip](https://github.com/Acellera/htmd/files/890593/equil.zip)

What could be possibly wrong with this ligand?

**Comment by j3mdamas** [comment]
Thanks Geri, give me some time

**Comment by mj-harvey** [comment]
charmm or amber?

**Comment by GerardBCN** [comment]
CHARMM

**Comment by mj-harvey** [comment]
confirmed. Not sure what's going on here.

**Comment by j3mdamas** [comment]
@raimis assigning it to you

**Comment by raimis** [comment]
Hi @GerardBCN 

Could you confirm, if the problem persists with *HTMD 1.9.5*, please.

**Comment by GerardBCN** [comment]
Hi @raimis , I want to parameterize few ligands including the one in this thread. Could you advise which is the current best practises for parameterization, i.e. which level of theory you recommend (preferably tested ones), etc. I think this effort can be useful to test the robustness of the current tool.

**Comment by raimis** [comment]
@GerardBCN 

I would recommend B3LYP theory, 6-31G* basis, and no implicit solvent for "normal" molecules.

Regarding *parameterize*, I have fixed several bugs recently, but more code refactoring is under way. Of course, it would be useful if you can shake the code to see what is still broken.

**Comment by raimis** [comment]
Are you going to parameterize for CHARMM or AMBER?

**Comment by GerardBCN** [comment]
CHARMM.

Parameterization fails at dihedral fitting:

```

 == Torsion fitting ==


Iteration 1

 == Fitting torsion C9-C7-C6-H6 ==

Creating new type cx0 from c for atom C9
Error in fitting
Could not find improper parameters for cx0-ce-cd-ss
Traceback (most recent call last):
  File "/shared/gerard/software/miniconda3/bin/parameterize", line 11, in <module>  
    sys.exit(main_parameterize())
  File "/shared/gerard/HTMD/htmd/htmd/parameterization/cli.py", line 241, in main_parameterize
    ret = mol.fitSoftTorsion(d, geomopt=args.geomopt)
  File "/shared/gerard/HTMD/htmd/htmd/parameterization/ffmolecule.py", line 425, in fitSoftTorsion
    self._makeDihedralUnique(phi_to_fit)
  File "/shared/gerard/HTMD/htmd/htmd/parameterization/ffmolecule.py", line 662, in _makeDihedralUnique
    self._duplicateTypeOfAtom(phi_to_fit.atoms[i])
  File "/shared/gerard/HTMD/htmd/htmd/parameterization/ffmolecule.py", line 766, in _duplicateTypeOfAtom
    ffe.evaluate(self.coords)
  File "/shared/gerard/HTMD/htmd/htmd/parameterization/ffevaluate.py", line 211, in evaluate
    ee['improper'] = self._evaluate_impropers(coords)
  File "/shared/gerard/HTMD/htmd/htmd/parameterization/ffevaluate.py", line 155, in _evaluate_impropers
    self.rtf.type_by_index[b3], self.rtf.type_by_index[b4])
  File "/shared/gerard/HTMD/htmd/htmd/parameterization/ff.py", line 544, in improperParam
    raise ValueError("Could not find improper parameters for %s-%s-%s-%s" % (n1, n2, n3, n4))
```
when starting from this mol2 file 
[mol.mol2.zip](https://github.com/Acellera/htmd/files/1248174/mol.mol2.zip)

**Comment by raimis** [comment]
@GerardBCN 

Thanks for your effort.

This looks interesting! It seemed, only AMBER had the problem with missing impropers.

Could you share all output files, please.

**Comment by j3mdamas** [comment]
@GerardBCN, by default, both CHARMM and Amber parameters are generated.

**Comment by GerardBCN** [comment]
There you go!

[blowup_mistery.zip](https://github.com/Acellera/htmd/files/1248236/blowup_mistery.zip)

**Comment by raimis** [comment]
@GerardBCN 

Could you also give an exact command you used to run the simulations, please.

**Comment by GerardBCN** [comment]
The simulation? or the parameterization? For the parameterization I used 

`parameterize -m mol.mol2 -n 8`

**Comment by raimis** [comment]
@GerardBCN 

The error message comes from AMBER, but it has already fixed in **HTMD 1.9.7**:
```
$ parameterize -m mol.mol2 

HTMD License accepted automatically. Check license here: https://raw.githubusercontent.com/Acellera/htmd/master/htmd/LICENCE.txt

For advanced features (e.g. parameterize) and to remove this message, we recommend registering. Run htmd_register in your terminal.

Please cite HTMD: Doerr et al.(2016)JCTC,12,1845. https://dx.doi.org/10.1021/acs.jctc.6b00049

HTMD Documentation at: https://www.htmd.org/docs/latest/

You are on the latest HTMD version (1.9.7).

Deprecation warning: "from htmd import *" will be deprecated. 
To import all HTMD shortcuts please from now on use "from htmd.ui import *"
 === List of arguments used ===

       mol:  mol.mol2  
      list:  False     
    charge:  None      
       rtf:  None      
       prm:  None      
    outdir:  ./        
   torsion:  all       
     ncpus:  8         
forcefield:  all       
     basis:  cc-pVDZ   
    theory:  B3LYP     
    vacuum:  True      
     nomin:  False     
     noesp:  False     
 notorsion:  False     
      exec:  inline    
    qmcode:  PSI4      
   freezeq:  None      
   geomopt:  True      

 === Parameterizing mol.mol2 ===

 === Fitting for FF CGenFF_2b6 ===

Dihedral 0: 12-7-6-19
Dihedral 1: 21-10-9-8
 Has equivalent dihedrals through symmetry: 
 Dihedral 8-9-10-20
Dihedral 2: 3-4-6-7
Got charge 0
Set charge 0
C1     C.4    CG331  !C.4(H.1)(H.1)(H.1)
C2     C.3%5A CG2R51 C.3%5 
C3     C.3%5A CG2R51 C.3%5(H.1)(C.3%5(C.3%5))(C.3%5)
C4     C.3%5A CG2R51 C.3%5 
C5     C.3%5A CG2R51 C.3%5 
S1     S.2%5A SG2R50 S.2%*A
C6     C.3    CG2D1  !C.3(!C)(H.1)([^O])
C7     C.3%5A CG2R51 C.3%5 
S2     S.2%5A SG2R50 S.2%*A
C8     C.3%5A CG2R53 C.3%5(N.2%5)(^C%5)
N1     N.3    NG321  N.3(H.1)(H.1)
N2     N.2%5A NG2R50 N.2%5 
C9     C.3%5A CG2R53 C.3%5(O.1)
O1     O.1    OG2D1  O.1(C.3%5)
H1     H.1    HGA3   H.1(C.4(H.1)(H.1))
H2     H.1    HGA3   H.1(C.4(H.1)(H.1))
H3     H.1    HGA3   H.1(C.4(H.1)(H.1))
H4     H.1    HGR51  H.1(C.3%5)
H5     H.1    HGR51  H.1(C.3%5)
H6     H.1    HGA4   H.1(C.3)
H7     H.1    HGP1   H.1(!N.3)
H8     H.1    HGP1   H.1(!N.3)
mol Success!
Net Charge: 0
Equivalent atom groups:
 C1
 C2
 C3
 C4
 C5
 S1
 C6
 C7
 S2
 C8
 N1
 N2
 C9
 O1
 H1 H2 H3
 H4
 H5
 H6
 H7 H8
Soft torsions:
 C9 C7 C6 H6
 H8 N1 C8 S2
 C4 C5 C6 C7

 == Minimizing ==

Running QM Calculations: 100% (1/1) [###########################################################################################################################] eta --:-- -

 == Charge fitting ==

Reusing previously-generated point cloud
Running QM Calculations: 100% (1/1) [###########################################################################################################################] eta --:-- |
Charge Chi^2 score : 0.022823 : GOOD
QM Dipole   : 2.507200 -5.110800 -0.049100 ; 5.692800
MM Dipole   : 2.545279 -5.119874 -0.051467 ; 5.717885
Dipole Chi^2 score : 0.001538 : GOOD


 == Torsion fitting ==


Iteration 1

 == Fitting torsion C9-C7-C6-H6 ==

Creating new type C253x0 from C253 for atom C9
Creating new type C251x0 from C251 for atom C7
Creating new type C2D1x0 from C2D1 for atom C6
Creating new type HGA4x0 from HGA4 for atom H6
Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 -
Omitting optimised QM pose (QM energy too high -833919.530812)
Omitting optimised QM pose (QM energy too high -833913.414394)
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:01 |
Torsion C9-C7-C6-H6 Chi^2 score : 0.144719 : GOOD

 == Fitting torsion H8-N1-C8-S2 ==

Creating new type HGP1x0 from HGP1 for atom H8
Creating new type N321x0 from N321 for atom N1
Creating new type C253x1 from C253 for atom C8
Creating new type S250x0 from S250 for atom S2
Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 -
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:01 \
Torsion H8-N1-C8-S2 Chi^2 score : 0.221927 : GOOD

 == Fitting torsion C4-C5-C6-C7 ==

Creating new type C251x1 from C251 for atom C4
Creating new type C251x2 from C251 for atom C5
Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 /
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:00 |
Torsion C4-C5-C6-C7 Chi^2 score : 1.143570 : GOOD

Iteration 2

 == Fitting torsion C9-C7-C6-H6 ==

Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 -
Omitting optimised QM pose (QM energy too high -833919.530812)
Omitting optimised QM pose (QM energy too high -833913.414394)
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:00 /
Torsion C9-C7-C6-H6 Chi^2 score : 0.083568 : GOOD

 == Fitting torsion H8-N1-C8-S2 ==

Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 \
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:01 \
Torsion H8-N1-C8-S2 Chi^2 score : 0.221146 : GOOD

 == Fitting torsion C4-C5-C6-C7 ==

Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 /
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:00 |
Torsion C4-C5-C6-C7 Chi^2 score : 1.140918 : GOOD
 Dihedral 0 relative error : -0.422551 
 Dihedral 1 relative error : -0.003519 - converged
 Dihedral 2 relative error : -0.002319 - converged

Iteration 3

 == Fitting torsion C9-C7-C6-H6 ==

Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 -
Omitting optimised QM pose (QM energy too high -833919.530812)
Omitting optimised QM pose (QM energy too high -833913.414394)
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:00 /
Torsion C9-C7-C6-H6 Chi^2 score : 0.083631 : GOOD

 == Fitting torsion H8-N1-C8-S2 ==

Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 \
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:01 |
Torsion H8-N1-C8-S2 Chi^2 score : 0.221146 : GOOD

 == Fitting torsion C4-C5-C6-C7 ==

Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 -
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:00 /
Torsion C4-C5-C6-C7 Chi^2 score : 1.140917 : GOOD
 Dihedral 0 relative error : 0.000763 - converged
 Dihedral 1 relative error : -0.000002 - converged
 Dihedral 2 relative error : -0.000001 - converged
 Fitting converged at iteration 3

 Fit of conformer energies: RMS 0.015469 Variance 0.998644

 == Diagnostic Energies == 

 Bond     : 17.715916
 Angle    : 63.609953
 Dihedral : 13.101732
 Improper : 0.000000
 Electro  : -106.269250
 VdW      : 2.850623


 == Output to ./parameters/CGenFF_2b6/b3lyp-cc-pVDZ-vacuum ==

 === Fitting for FF GAFF2 ===

Dihedral 0: 12-7-6-19
Dihedral 1: 21-10-9-8
 Has equivalent dihedrals through symmetry: 
 Dihedral 8-9-10-20
Dihedral 2: 3-4-6-7

Unknown bond type for BOND(C1-C2:un), assuming it is a single bond
Unknown bond type for BOND(C1-H1:un), assuming it is a single bond
Unknown bond type for BOND(C1-H2:un), assuming it is a single bond
Unknown bond type for BOND(C1-H3:un), assuming it is a single bond
Unknown bond type for BOND(C2-C3:un), assuming it is a single bond
Unknown bond type for BOND(C2-S1:un), assuming it is a single bond
Unknown bond type for BOND(C3-C4:un), assuming it is a single bond
Unknown bond type for BOND(C3-H4:un), assuming it is a single bond
Unknown bond type for BOND(C4-C5:un), assuming it is a single bond
Unknown bond type for BOND(C4-H5:un), assuming it is a single bond
Unknown bond type for BOND(C5-S1:un), assuming it is a single bond
Unknown bond type for BOND(C5-C6:un), assuming it is a single bond
Unknown bond type for BOND(C6-C7:un), assuming it is a single bond
Unknown bond type for BOND(C6-H6:un), assuming it is a single bond
Unknown bond type for BOND(C7-S2:un), assuming it is a single bond
Unknown bond type for BOND(C7-C9:un), assuming it is a single bond
Unknown bond type for BOND(S2-C8:un), assuming it is a single bond
Unknown bond type for BOND(C8-N1:un), assuming it is a single bond
Unknown bond type for BOND(C8-N2:un), assuming it is a single bond
Unknown bond type for BOND(N1-H7:un), assuming it is a single bond
Unknown bond type for BOND(N1-H8:un), assuming it is a single bond
Unknown bond type for BOND(N2-C9:un), assuming it is a single bond

Warning: ATOM N2 has unfilled valence, assuming the linked atom name (in other residue) is "M"
         change "M" to "-M" if ATOM N2 is linked to the immediate previous residue
         change "M" to "+M" if ATOM N2 is linked to the immediate after residueUnknown bond type for BOND(C9-O1:un), assuming it is a single bond
Net Charge: 0
Equivalent atom groups:
 C1
 C2
 C3
 C4
 C5
 S1
 C6
 C7
 S2
 C8
 N1
 N2
 C9
 O1
 H1 H2 H3
 H4
 H5
 H6
 H7 H8
Soft torsions:
 C9 C7 C6 H6
 H8 N1 C8 S2
 C4 C5 C6 C7

 == Minimizing ==

Running QM Calculations: 100% (1/1) [###########################################################################################################################] eta --:-- \

 == Charge fitting ==

Reusing previously-generated point cloud
Running QM Calculations: 100% (1/1) [###########################################################################################################################] eta --:-- /
Charge Chi^2 score : 0.022823 : GOOD
QM Dipole   : 2.507200 -5.110800 -0.049100 ; 5.692800
MM Dipole   : 2.545279 -5.119874 -0.051467 ; 5.717885
Dipole Chi^2 score : 0.001538 : GOOD


 == Torsion fitting ==


Iteration 1

 == Fitting torsion C9-C7-C6-H6 ==

Creating new type cx0 from c for atom C9
Creating new type cdx0 from cd for atom C7
Creating new type cex0 from ce for atom C6
Creating new type hax0 from ha for atom H6
Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 \
Omitting optimised QM pose (QM energy too high -833919.530812)
Omitting optimised QM pose (QM energy too high -833913.414394)
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:01 -
Torsion C9-C7-C6-H6 Chi^2 score : 0.024603 : GOOD

 == Fitting torsion H8-N1-C8-S2 ==

Creating new type hnx0 from hn for atom H8
Creating new type nvx0 from nv for atom N1
Creating new type ccx0 from cc for atom C8
Creating new type ssx0 from ss for atom S2
Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 |
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:01 \
Torsion H8-N1-C8-S2 Chi^2 score : 0.030446 : GOOD

 == Fitting torsion C4-C5-C6-C7 ==

Creating new type cdx1 from cd for atom C4
Creating new type ccx1 from cc for atom C5
Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 /
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:01 |
Torsion C4-C5-C6-C7 Chi^2 score : 0.062544 : GOOD

Iteration 2

 == Fitting torsion C9-C7-C6-H6 ==

Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 -
Omitting optimised QM pose (QM energy too high -833919.530812)
Omitting optimised QM pose (QM energy too high -833913.414394)
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:01 /
Torsion C9-C7-C6-H6 Chi^2 score : 0.023251 : GOOD

 == Fitting torsion H8-N1-C8-S2 ==

Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 \
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:01 -
Torsion H8-N1-C8-S2 Chi^2 score : 0.030446 : GOOD

 == Fitting torsion C4-C5-C6-C7 ==

Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 |
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:01 \
Torsion C4-C5-C6-C7 Chi^2 score : 0.062549 : GOOD
 Dihedral 0 relative error : -0.054944 
 Dihedral 1 relative error : 0.000024 - converged
 Dihedral 2 relative error : 0.000073 - converged

Iteration 3

 == Fitting torsion C9-C7-C6-H6 ==

Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 /
Omitting optimised QM pose (QM energy too high -833919.530812)
Omitting optimised QM pose (QM energy too high -833913.414394)
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:01 |
Torsion C9-C7-C6-H6 Chi^2 score : 0.023251 : GOOD

 == Fitting torsion H8-N1-C8-S2 ==

Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 -
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:01 /
Torsion H8-N1-C8-S2 Chi^2 score : 0.030446 : GOOD

 == Fitting torsion C4-C5-C6-C7 ==

Running QM Calculations: 100% (36/36) [#########################################################################################################################] eta 00:00 \
Fitting: 100% (64/64) [#########################################################################################################################################] eta 00:01 -
Torsion C4-C5-C6-C7 Chi^2 score : 0.062549 : GOOD
 Dihedral 0 relative error : -0.000001 - converged
 Dihedral 1 relative error : -0.000000 - converged
 Dihedral 2 relative error : 0.000000 - converged
 Fitting converged at iteration 3

 Fit of conformer energies: RMS 0.001248 Variance 0.999890

 == Diagnostic Energies == 

 Bond     : 2.904292
 Angle    : 10.117188
 Dihedral : -3.629512
 Improper : 0.000654
 Electro  : -83.467648
 VdW      : 0.238339


 == Output to ./parameters/GAFF2/b3lyp-cc-pVDZ-vacuum ==
```

**Comment by GerardBCN** [comment]
Damn, new htmd versions come out like croissants in a bakery. Thank you!

**Comment by raimis** [comment]
We are working hard... :D

**Comment by raimis** [comment]
@GerardBCN Does the simulation of the molecule still blows up during MD?

**Comment by GerardBCN** [comment]
I didn't try. Should I use the CHARMM parameters I got with 1.9.6?

**Comment by raimis** [comment]
It is better to use **HTMD 1.9.7**. Just rerun the fitting with existing QM data.

**Comment by GerardBCN** [comment]
Doesn't blow up in CHARMM! congratz! so I guess we can close the thread  :)
