### ISSUE TITLE
parameterize error:  KeyError

### ISSUE THREAD

**Issue by cuzzo87** [Acellera/htmd#341]
[mol.txt](https://github.com/Acellera/htmd/files/1010773/mol.txt)

Performing a fast parametrization I got the following error:

cmd ``` parameterize -m 4ddk_ligand.mol2 --no-min --no-esp --no-torsions ```

```
 == Diagnostic Energies == 
Traceback (most recent call last):
  File "/shared/acellera/miniconda3/bin/parameterize", line 6, in <module>
    sys.exit(htmd.parameterization.cli.main_parameterize())
  File "/shared/acellera/miniconda3/lib/python3.6/site-packages/htmd/parameterization/cli.py", line 291, in main_parameterize
    printEnergies(mol)
  File "/shared/acellera/miniconda3/lib/python3.6/site-packages/htmd/parameterization/cli.py", line 72, in printEnergies
    ffe = FFEvaluate(m)
  File "/shared/acellera/miniconda3/lib/python3.6/site-packages/htmd/parameterization/ffevaluate.py", line 21, in __init__
    self.mol.charge[i] = self.rtf.charge_by_name[self.mol.name[i]]
KeyError: 'OAA1'
```

**Comment by raimis** [comment]
@j3mdamas can you reassign this to me. It is related with #397.

**Comment by j3mdamas** [comment]
Done

**Comment by raimis** [comment]
@cuzzo87 

**HTMD 1.9.5** don't crash with the structure.

Could  you confirm, it solves the issue, please!

**Comment by j3mdamas** [comment]
@cuzzo87, any news?

**Comment by cuzzo87** [comment]
I tried it again and now the atom is recognize. I consider it fixed
