### ISSUE TITLE
QM Optimization failed in parameterize

### ISSUE THREAD

**Issue by jeiros** [Acellera/htmd#348]
Hi,

I'm trying to parameterize a small molecule with your `parameterize` tool. I install htmd on a fresh Python 3.5 conda environment on a CentOs 7 machine:

```bash
conda create -n htmd-py35 python=3.5 -y
source activate htmd-py35
conda install -c acellera htmd -y
```
which installs htmd version 1.7.32 and psi4 version 1.0.54 (full conda [env](http://lpaste.net/raw/3890600261135106048) for completeness)

[Here](http://lpaste.net/raw/1346336307286114304) is the molecule I'm trying to parameterize.

I'm running a simple `parameterize -m EGCG.mol2 -f GAFF2` command, which produces this [output](http://lpaste.net/raw/4344094643760136192) before crashing:
```
Traceback (most recent call last):
  File "/home/je714/anaconda3/envs/htmd-py35/bin/parameterize", line 6, in <module>
    sys.exit(htmd.parameterization.cli.main_parameterize())
  File "/home/je714/anaconda3/envs/htmd-py35/lib/python3.5/site-packages/htmd/parameterization/cli.py", line 180, in main_parameterize
    mol.minimize()
  File "/home/je714/anaconda3/envs/htmd-py35/lib/python3.5/site-packages/htmd/parameterization/ffmolecule.py", line 163, in minimize
    raise RuntimeError("QM Optimization failed")
RuntimeError: QM Optimization failed
```

I've been able to optimize this molecule before with a standalone installation of Psi4. But I want to learn to use your tool since it will help me automate the process (and ultimately have to parameterize other small molecules too). 

I have a more general question: does your tool accept different conformations of a ligand to do multi conformational RESP fitting? For example, I am able to generate different conformers via [rdkit](http://www.rdkit.org/) and store them all in a mol2 file. Would that improve the quality of the charges that are generated?

Thanks for any suggestions!

Edit: I also tried with Benzamidine, from the [tutorial](https://www.htmd.org/docs/latest/acetk/parameterize/parameterize-tutorial.html) and got a similar Traceback
<details>

```
$ parameterize -m ben.mol2

Please cite HTMD: Doerr et al.(2016)JCTC,12,1845. https://dx.doi.org/10.1021/acs.jctc.6b00049

HTMD Documentation at: https://www.htmd.org/docs/latest/

You are on the latest HTMD version (1.7.32).

 === List of arguments used ===

    qmcode:  PSI4
   torsion:  all
    charge:  None
    theory:  B3LYP
   freezeq:  None
    outdir:  ./
      exec:  inline
     basis:  cc-pVDZ
     nomin:  False
     noesp:  False
    vacuum:  False
       rtf:  None
     ncpus:  4
       prm:  None
      list:  False
       mol:  ben.mol2
 notorsion:  False
   geomopt:  True
forcefield:  all

 === Parameterizing ben.mol2 ===

 === Fitting for FF CGenFF_2b6 ===

Dihedral 0: 1-0-6-7
 Has equivalent dihedrals through symmetry:
 Dihedral 5-0-6-7
Dihedral 1: 0-6-7-14
Dihedral 2: 0-6-8-15
 Has equivalent dihedrals through symmetry:
 Dihedral 0-6-8-16
Got charge 1
Set charge 1
C1     C.3%6A CG2R61 C.3%6A
C2     C.3%6A CG2R61 C.3%6A
C3     C.3%6A CG2R61 C.3%6A
C4     C.3%6A CG2R61 C.3%6A
C5     C.3%6A CG2R61 C.3%6A
C6     C.3%6A CG2R61 C.3%6A
C7     C.3    CG2DC? !C.3(C)([^O])(=C.3(C.3(=C.3)))
N1     N.2    NG2D1  !N.2
N2     N.3    NG321  N.3(H.1)(H.1)
H1     H.1    HGR61  H.1(C.3%6)
H2     H.1    HGR61  H.1(C.3%6)
H3     H.1    HGR61  H.1(C.3%6)
H4     H.1    HGR61  H.1(C.3%6)
H5     H.1    HGR61  H.1(C.3%6)
H6     H.1    HGP1   H.1(!N.2)
H7     H.1    HGP1   H.1(!N.3)
H8     H.1    HGP1   H.1(!N.3)
mol Success!
Net Charge: 1
Equivalent atom groups:
 C1
 C2 C6
 C3 C5
 C4
 C7
 N1
 N2
 H1 H5
 H2 H4
 H3
 H6
 H7 H8
Soft torsions:
 C2 C1 C7 N1
 C1 C7 N1 H6
 C1 C7 N2 H7

 == Minimizing ==

Traceback (most recent call last):
  File "/home/je714/anaconda3/envs/htmd-py35/share/psi4/python/inputparser.py", line 709, in process_input
    temp = re.sub(pcm, process_pcm_command, temp)
  File "/home/je714/anaconda3/envs/htmd-py35/share/psi4/python/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/je714/anaconda3/envs/htmd-py35/share/psi4/python/inputparser.py", line 378, in process_pcm_command
    import pcmsolver
  File "/home/je714/anaconda3/envs/htmd-py35/bin/pcmsolver.py", line 37, in <module>
    import getkw
  File "/home/je714/anaconda3/envs/htmd-py35/bin/getkw.py", line 23, in <module>
    from pyparsing import \
ImportError: No module named pyparsing
Running QM Calculations: 100% (1/1) [#################################################################] eta --:-- -
Traceback (most recent call last):
  File "/home/je714/anaconda3/envs/htmd-py35/bin/parameterize", line 6, in <module>
    sys.exit(htmd.parameterization.cli.main_parameterize())
  File "/home/je714/anaconda3/envs/htmd-py35/lib/python3.5/site-packages/htmd/parameterization/cli.py", line 180, in main_parameterize
    mol.minimize()
  File "/home/je714/anaconda3/envs/htmd-py35/lib/python3.5/site-packages/htmd/parameterization/ffmolecule.py", line 163, in minimize
    raise RuntimeError("QM Optimization failed")
RuntimeError: QM Optimization failed
```

<\details>

**Comment by j3mdamas** [comment]
Hi,

We currently do not support multi-configurational RESP fitting, IIRC.

The issue you were experiencing has been reported in the past (#313) and should be solved in version 1.8.0, that was just released. For that version, I recommend installing from scratch, instead of updating. `conda install htmd -c acellera -c psi4`.
