### ISSUE TITLE
OpenMM cannot read a HTMD-generated PSF file

### ISSUE THREAD

**Issue by raimis** [Acellera/htmd#398]
Generate a PSF file of benzamidine with *HTMD* and try to read with *OpenMM*:
```python
# test.py

import os
from htmd.home import home
from htmd.molecule.molecule import Molecule
from simtk.openmm.app import CharmmPsfFile

molFile = os.path.join(home('building-protein-ligand'), 'benzamidine.mol2')
mol = Molecule(molFile)
mol.write('mol.psf')

psf = CharmmPsfFile('mol.psf')
```
```bash
$ python test.py

HTMD License accepted automatically. Check license here: https://raw.githubusercontent.com/Acellera/htmd/master/htmd/LICENCE.txt

For advanced features (e.g. parameterize) and to remove this message, we recommend registering. Run htmd_register in your terminal.

Please cite HTMD: Doerr et al.(2016)JCTC,12,1845. https://dx.doi.org/10.1021/acs.jctc.6b00049

HTMD Documentation at: https://www.htmd.org/docs/latest/

You are on the latest HTMD version (unpackaged : /home/raimis/opt/miniconda3/envs/htmd/lib/python3.6/site-packages/htmd-1.9.1-py3.6.egg/htmd).

HTMD: Logging setup failed
Deprecation warning: "from htmd import *" will be deprecated. 
To import all HTMD shortcuts please from now on use "from htmd.ui import *"
invalid literal for int() with base 10: '!NGRP'
Traceback (most recent call last):
  File "/home/raimis/opt/miniconda3/envs/htmd/lib/python3.6/site-packages/simtk/openmm/app/charmmpsffile.py", line 400, in _convert
    return type(string)
ValueError: invalid literal for int() with base 10: '!NGRP'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test2.py", line 11, in <module>
    psf = CharmmPsfFile('mol.psf')
  File "/home/raimis/opt/miniconda3/envs/htmd/lib/python3.6/site-packages/simtk/openmm/app/charmmpsffile.py", line 73, in newfunc
    return func(*args, **kwargs)
  File "/home/raimis/opt/miniconda3/envs/htmd/lib/python3.6/site-packages/simtk/openmm/app/charmmpsffile.py", line 194, in __init__
    sec, ptr, data = CharmmPsfFile._parse_psf_section(psf)
  File "/home/raimis/opt/miniconda3/envs/htmd/lib/python3.6/site-packages/simtk/openmm/app/charmmpsffile.py", line 460, in _parse_psf_section
    data.extend([conv(w, int, 'PSF data') for w in words])
  File "/home/raimis/opt/miniconda3/envs/htmd/lib/python3.6/site-packages/simtk/openmm/app/charmmpsffile.py", line 460, in <listcomp>
    data.extend([conv(w, int, 'PSF data') for w in words])
  File "/home/raimis/opt/miniconda3/envs/htmd/lib/python3.6/site-packages/simtk/openmm/app/charmmpsffile.py", line 403, in _convert
    raise CharmmPSFError('Could not convert %s' % message)
simtk.openmm.app.internal.charmm.exceptions.CharmmPSFError: Could not convert PSF data
```
As the error message says, there is something strange with *!NGRP* section:
```
...
         0 !NACC: acceptors

         0 !NNB: acceptors

         0          0 !NGRP
```

**Comment by raimis** [comment]
@stefdoerr You are the last you modified *PSFWriter*, could you explain about that additional "0" before "!NGRP", please.

**Comment by stefdoerr** [comment]
Nope, I just moved Matt's code into the new `writers.py` file. 
First I assumed it was a typo but after searching online it seems to be correct:

https://heller.userweb.mwn.de/ego/manual/node88.html
http://archive.ambermd.org/201408/0110.html

Is the section after that line empty? It might be an issue that we are putting zeros before the sections which is wrong. I don't know exactly what those integers are supposed to be but at least in NGRP it seems to correspond to the number of groups:

https://github.com/ParmEd/ParmEd/blob/master/parmed/charmm/psf.py#L308

**Comment by raimis** [comment]
Thanks, @stefdoerr! The error message was misleading, the problem was the previous section. I'll fix it.
