### ISSUE TITLE
antechamber: Fatal Error on demo

### ISSUE THREAD

**Issue by tonigi** [Acellera/htmd#446]
Running the first demo `parameterize -m ben.mol2 --no-min --no-esp --no-torsions -o ./param-ben-noqm`, i get this

```
-- Check Weird Bonds --
/Users/toni/anaconda3/bin/to_be_dispatched/antechamber: Fatal Error!
Weird atomic valence (3) for atom (ID: 1, Name: C1).
       Possible open valence.
Traceback (most recent call last):
  File "/Users/toni/anaconda3/bin/parameterize", line 11, in <module>
    sys.exit(main_parameterize())
  File "/Users/toni/anaconda3/lib/python3.6/site-packages/htmd/parameterization/cli.py", line 171, in main_parameterize
    outdir=args.outdir)
  File "/Users/toni/anaconda3/lib/python3.6/site-packages/htmd/parameterization/ffmolecule.py", line 101, in __init__
    fftype = FFType(self, method=self.method)
  File "/Users/toni/anaconda3/lib/python3.6/site-packages/htmd/parameterization/fftype.py", line 89, in __init__
    raise RuntimeError('"antechamber" failed')
RuntimeError: "antechamber" failed
```

Not sure if the valence causes the failure.

**Comment by raimis** [comment]
I guess, `antechamber` has a similar problem to `match-typer`.

Actually, most of `parameterize` tests on Travis are disable for Mac.

**Comment by tonigi** [comment]
Hm... does not seem a path thing.

**Comment by tonigi** [comment]
Somehow fixed upgrading ambermini and removing a possibly conflicting `ambertools`...
