### ISSUE TITLE
No dihedrals causes IndexError: list index out of range

### ISSUE THREAD

**Issue by quantumania** [Acellera/htmd#542]
The MOL2 file is here: https://isu.box.com/s/05f4fzbojb0tujimejtnuzeg80gt3r9m
This is htmd 1.11.7 PSI4 output shows both minimization and esp jobs completed successfully. See the log below:

 === Arguments ===
 filename: 5TVN_Prepped_LOR.mol2
charge: 1
list: False
rtf_prm: None
forcefield: ['GAFF2']
fix_charge: []
dihedral: []
code: Psi4
theory: B3LYP
basis: cc-pVDZ
environment: vacuum
minimize: True
fit_charges: True
fit_dihedral: True
optimize_dihedral: True
queue: local
ncpus: 8
memory: None
groupname: None
outdir: 5TVN_Prepped_LOR
seed: 20170920
fake_qm: False

 === Parameterizing 5TVN_Prepped_LOR.mol2 ===

 === Fitting for GAFF2 ===

 == Molecule report ==

Total number of atoms: 28
Total charge: 1
Equivalent atom groups:
  CL1
  N1
  C1
  C2
  C3
  C4
  C5
  C6
  C7
  C8
  C9
  C10
  C11
  H1, H2
  H3
  H4, H5
  H6, H7
  H8, H9
  H10, H11, H12
Rotatable dihedral angles:

 == Minimizing ==

 == Fitting ESP charges ==

/garlic/apps/anaconda3/envs/htmd_1.11.7/lib/python3.6/site-packages/htmd/parameterization/ffmolecule.py:201: RuntimeWarning: invalid value encountered in true_divide
  return np.dot(self.masses, self.coords[:, :, self.frame])/np.sum(self.masses)
MM dipole cannot be computed. Check if elements are detected correctly.

 == Fitting dihedral angle parameters ==

Traceback (most recent call last):
  File "/garlic/apps/anaconda3/envs/htmd_1.11.7/bin/parameterize", line 11, in <module>
    sys.exit(main_parameterize())
  File "/garlic/apps/anaconda3/envs/htmd_1.11.7/lib/python3.6/site-packages/htmd/parameterization/cli.py", line 263, in main_parameterize
    mol.fitDihedrals(dihedrals, args.optimize_dihedral)
  File "/garlic/apps/anaconda3/envs/htmd_1.11.7/lib/python3.6/site-packages/htmd/parameterization/ffmolecule.py", line 325, in fitDihedrals
    df.run()
  File "/garlic/apps/anaconda3/envs/htmd_1.11.7/lib/python3.6/site-packages/htmd/parameterization/dihedral.py", line 400, in run
    self._fit()
  File "/garlic/apps/anaconda3/envs/htmd_1.11.7/lib/python3.6/site-packages/htmd/parameterization/dihedral.py", line 353, in _fit
    self.molecule._prm.updateDihedral(self.parameters)
  File "/garlic/apps/anaconda3/envs/htmd_1.11.7/lib/python3.6/site-packages/htmd/parameterization/ff.py", line 409, in updateDihedral
    if phi[0].types[0] != p.types[0] or phi[0].types[1] != p.types[1] or phi[0].types[2] != p.types[2] or \
IndexError: list index out of range

**Comment by raimis** [comment]
@quantumania 

It seems, you posted a wrong link. I can download `5TVN_Prepped_ROP.mol2`, but not `5TVN_Prepped_LOR.mol2`.

**Comment by quantumania** [comment]
Sorry, here is the correct MOL2 file: 5TVN_Prepped_LOR.mol2
https://isu.box.com/s/8vamh2uq8gk2h6ak8h7hjnsyu3tjuqij

**Comment by quantumania** [comment]
Another bug report. This may be an easy fix related to CGENFF atom typing.

MOL2 file https://isu.box.com/s/1mi3sjt4aemaiadypigna8to01jgqnmc
Command: parameterize 5TUD_Prepped_ERM.mol2 -c 1 -n 4 --forcefield CGENFF -o 5TUD_Prepped_ERM 

 === Fitting for CGenFF_2b6 ===

Traceback (most recent call last):
  File "/garlic/apps/anaconda3/envs/htmd/bin/parameterize", line 11, in <module>
    sys.exit(main_parameterize())
  File "/garlic/apps/anaconda3/envs/htmd/lib/python3.6/site-packages/htmd/parameterization/cli.py", line 186, in main_parameterize
    outdir=args.outdir)
  File "/garlic/apps/anaconda3/envs/htmd/lib/python3.6/site-packages/htmd/parameterization/ffmolecule.py", line 93, in __init__
    self.atomtype[:] = [self._rtf.type_by_name[name] for name in self.name]
  File "/garlic/apps/anaconda3/envs/htmd/lib/python3.6/site-packages/htmd/parameterization/ffmolecule.py", line 93, in <listcomp>
    self.atomtype[:] = [self._rtf.type_by_name[name] for name in self.name]
KeyError: 'HO1'

**Comment by j3mdamas** [comment]
so, @raimis, the problem here is only that there are no dihedrals to parameterize on this molecule, right? I've changed the title accordingly and deleted one other report from @quantumania which is already on another issue

**Comment by raimis** [comment]
Yes!

**Comment by quantumania** [comment]
Correct. Looks like an easy fix.
