### ISSUE TITLE
parameterization of ACE and NME - does not detect torsions

### ISSUE THREAD

**Issue by nesilin** [Acellera/htmd#61]
this file:
```
@<TRIPOS>MOLECULE
ACT.pdb
 7 6 0 0 0
SMALL
GASTEIGER

@<TRIPOS>ATOM
      1  C         -0.0720    0.0000    0.0000 C.2     0  ACT0        0.3530
      2  O         -0.6820    1.0560    0.0000 O.co2   0  ACT0       -0.2467
      3  OXT       -0.6820   -1.0560    0.0000 O.co2   0  ACT0       -0.2467
      4  CH3        1.4350    0.0000    0.0000 C.3     0  ACT0        0.0375
      5  H1         1.7990    0.0000    1.0280 H       0  ACT0        0.0343
      6  H2         1.7990   -0.8900   -0.5140 H       0  ACT0        0.0343
      7  H3         1.7990    0.8900   -0.5140 H       0  ACT0        0.0343
@<TRIPOS>BOND
     1     1     4    1
     2     1     2   ar
     3     1     3   ar
     4     4     5    1
     5     4     6    1
     6     4     7    1
```

This output:
```
2016-06-14 11:47:29,927 - htmd.parameterize - INFO - run(): Step [qm_1d_scan] in dir [/home/ines/.htmd/gaamp/act/230-qm_1d_scan]
2016-06-14 11:47:29,927 - htmd.parameterize - INFO - completed(): Expected outputfile [mol.prm] not present
2016-06-14 11:47:29,928 - htmd.parameterize - INFO - run(): Running step [qm_1d_scan]
Running step [230] [qm_1d_scan]
2016-06-14 11:47:29,928 - htmd.parameterize - INFO -  Running step [230] 	[qm_1d_scan] 
2016-06-14 11:47:29,957 - htmd.parameterize - INFO - completed(): Expected outputfile [tor-1D-idx-*.dat] not present
Traceback (most recent call last):
  File "parame3.py", line 9, in <module>
    param = Parameterisation(config=config)
  File "/home/ines/miniconda3/lib/python3.5/site-packages/htmd/parameterize/parameterisation.py", line 96, in __init__
    self.run()
  File "/home/ines/miniconda3/lib/python3.5/site-packages/htmd/parameterize/parameterisation.py", line 99, in run
    self.stepset.run(self.directory, param=self)
  File "/home/ines/miniconda3/lib/python3.5/site-packages/htmd/parameterize/step.py", line 58, in run
    raise ValueError( "run(): Step [" +  i.name + "] did not produce the expected output: " + str( i.missing(directory)) + " in directory " + directory )
ValueError: run(): Step [qm_1d_scan] did not produce the expected output: ['tor-1D-idx-*.dat', 'qm-1d-states.dat', 'n_rotamer.txt'] in directory /home/ines/.htmd/gaamp/act/230-qm_1d_scan
```

**Comment by nesilin** [comment]
Now the methylamine:
Input file: 

```
@<TRIPOS>MOLECULE
nme_h.pdb
 8 7 0 0 0
SMALL
GASTEIGER

@<TRIPOS>ATOM
      1  N         25.1930   13.0570   24.1750 N.4     1  NME1        0.2163
      2  C         26.3230   12.9170   25.1300 C.3     1  NME1       -0.0466
      3  H01       26.6650   11.8820   25.1390 H       1  NME1        0.0776
      4  H02       24.8740   12.1410   23.8930 H       1  NME1        0.1991
      5  H03       25.9920   13.2000   26.1290 H       1  NME1        0.0776
      6  H04       25.5000   13.5720   23.3620 H       1  NME1        0.1991
      7  H05       27.1420   13.5670   24.8210 H       1  NME1        0.0776
      8  H06       24.4350   13.5540   24.6210 H       1  NME1        0.1991
@<TRIPOS>BOND
     1     1     2    1
     2     1     4    1
     3     1     6    1
     4     1     8    1
     5     2     3    1
     6     2     5    1
     7     2     7    1

```
Output error:
```
Running step [230] [qm_1d_scan]
2016-06-14 12:31:13,995 - htmd.parameterize - INFO -  Running step [230] 	[qm_1d_scan] 
2016-06-14 12:31:14,021 - htmd.parameterize - INFO - completed(): Expected outputfile [tor-1D-idx-*.dat] not present
Traceback (most recent call last):
  File "parame3.py", line 9, in <module>
    param = Parameterisation(config=config)
  File "/home/ines/miniconda3/lib/python3.5/site-packages/htmd/parameterize/parameterisation.py", line 96, in __init__
    self.run()
  File "/home/ines/miniconda3/lib/python3.5/site-packages/htmd/parameterize/parameterisation.py", line 99, in run
    self.stepset.run(self.directory, param=self)
  File "/home/ines/miniconda3/lib/python3.5/site-packages/htmd/parameterize/step.py", line 58, in run
    raise ValueError( "run(): Step [" +  i.name + "] did not produce the expected output: " + str( i.missing(directory)) + " in directory " + directory )
ValueError: run(): Step [qm_1d_scan] did not produce the expected output: ['tor-1D-idx-*.dat', 'qm-1d-states.dat', 'n_rotamer.txt'] in directory /home/ines/.htmd/gaamp/nme_h.mol2/230-qm_1d_scan
```
Script runned:
```
from htmd import *
import re
from htmd.parameterize import Configuration, Parameterisation
glutamate = Molecule('./nme_h.mol2')
config = Configuration()
config.FileName = "./nme_h.mol2"
config.JobName = "nme_h.mol2"
config.NetCharge = "+1"
param = Parameterisation(config=config)
paramfiles = param.getParameters()
shutil.copyfile(paramfiles['RTF'], "nme_h.rtf")
shutil.copyfile(paramfiles['PRM'], "nme_h.prm")
shutil.copyfile(paramfiles['PDB'], "nme_h.pdb")
```

**Comment by nesilin** [comment]
As suggested two days ago I have done the parametrization of methylamine with https://cgenff.paramchem.org/ 
The  CGenFF program takes as input a pdb or mol2 file and gives as output an str file. In order to obtain the topology file (.rtf) and the parameters file (.prm) I have used the program split_stream.pl available here: https://github.com/tonigi/vmd_utilities/blob/master/charmm_utilities/split_stream.pl  as suggested in this presentation: https://www.acellera.com/wp-content/uploads/2013/11/session2.-Automatic-ligand-parametrization.pdf . What this program does is to convert the .str file into the .rtf file and .prm. 
However, when we have tried to built the system with those parameter files it has reported the following error:
```
ERROR: failed on end of segment
MOLECULE DESTROYED BY FATAL ERROR!  Use resetpsf to start over.
    while executing
"segment L {
	pdb segmentL.pdb
	first none
	last none
}"
    (file "./build.vmd" line 168)
2016-06-17 13:22:08,779 - htmd.builder.charmm - WARNING - Failed to set coordinates for 1 atoms.
2016-06-17 13:22:08,779 - htmd.builder.charmm - WARNING - Please check /home/student1/avarela/DRUGG/acetate_adaptative_sampling/docked/build/1/log.txt for further information.
2016-06-17 13:22:08,780 - htmd.builder.charmm - INFO - Finished building.
Traceback (most recent call last):
  File "drugabbility_project.py", line 45, in <module>
    moltbuilt.append(charmm.build(smol, topo=topos, param=params, outdir='./docked/build/{}/'.format(i+1), saltconc=0.15))
  File "/home/student1/miniconda3/lib/python3.5/site-packages/htmd/builder/charmm.py", line 260, in build
    raise BuildError('No structure pdb/psf file was generated. Check {} for errors in building.'.format(logpath))
htmd.builder.charmm.BuildError: 'No structure pdb/psf file was generated. Check /home/student1/avarela/DRUGG/acetate_adaptative_sampling/docked/build/1/log.txt for errors in building.'
```

The .rtf file is: 
```
* Topologies generated by
* CHARMM General Force Field (CGenFF) program version 1.0.0
*
36 1

! "penalty" is the highest penalty score of the associated parameters.
! Penalties lower than 10 indicate the analogy is fair; penalties between 10
! and 50 mean some basic validation is recommended; penalties higher than
! 50 indicate poor analogy and mandate extensive validation/optimization.

RESI /scrat       1.000 ! param penalty=   0.000 ; charge penalty=   0.000
GROUP            ! CHARGE   CH_PENALTY
ATOM N      NG3P3  -0.300 !    0.000
ATOM C      CG334   0.040 !    0.000
ATOM H01    HGA3    0.090 !    0.000
ATOM H02    HGP2    0.330 !    0.000
ATOM H03    HGA3    0.090 !    0.000
ATOM H04    HGP2    0.330 !    0.000
ATOM H05    HGA3    0.090 !    0.000
ATOM H06    HGP2    0.330 !    0.000

BOND N    C   
BOND N    H02 
BOND N    H04 
BOND N    H06 
BOND C    H01 
BOND C    H03 
BOND C    H05 

END
```
The .prm file is:
```
* Parameters generated by analogy by
* CHARMM General Force Field (CGenFF) program version 1.0.0
*

! Penalties lower than 10 indicate the analogy is fair; penalties between 10
! and 50 mean some basic validation is recommended; penalties higher than
! 50 indicate poor analogy and mandate extensive validation/optimization.

BONDS
CG334  NG3P3   200.00     1.4800 ! PROT new stretch and bend; methylammonium (KK 03/10/92)
CG334  HGA3    322.00     1.1110 ! PROT alkane update, adm jr., 3/2/92
NG3P3  HGP2    403.00     1.0400 ! PROT new stretch and bend; methylammonium (KK 03/10/92)

ANGLES
NG3P3  CG334  HGA3     45.00    107.50   35.00   2.10100 ! PROT methylammonium (KK 03/10/92)
HGA3   CG334  HGA3     35.50    108.40    5.40   1.80200 ! PROT alkane update, adm jr., 3/2/92
CG334  NG3P3  HGP2     30.00    109.50   20.00   2.07400 ! PROT new stretch and bend; methylammonium (KK 03/10/92)
HGP2   NG3P3  HGP2     44.00    109.50 ! PROT new stretch and bend; methylammonium (KK 03/10/92)

DIHEDRALS
HGA3   CG334  NG3P3  HGP2       0.0900  3     0.00 ! PROT fine-tuned to ab initio; METHYLAMMONIUM, KK 03/10/92

IMPROPERS

END
```
The .str file from CGenFF:
```
* Toppar stream file generated by
* CHARMM General Force Field (CGenFF) program version 1.0.0
* For use with CGenFF version 3.0.1
*

read rtf card append
* Topologies generated by
* CHARMM General Force Field (CGenFF) program version 1.0.0
*
36 1

! "penalty" is the highest penalty score of the associated parameters.
! Penalties lower than 10 indicate the analogy is fair; penalties between 10
! and 50 mean some basic validation is recommended; penalties higher than
! 50 indicate poor analogy and mandate extensive validation/optimization.

RESI /scrat       1.000 ! param penalty=   0.000 ; charge penalty=   0.000
GROUP            ! CHARGE   CH_PENALTY
ATOM N      NG3P3  -0.300 !    0.000
ATOM C      CG334   0.040 !    0.000
ATOM H01    HGA3    0.090 !    0.000
ATOM H02    HGP2    0.330 !    0.000
ATOM H03    HGA3    0.090 !    0.000
ATOM H04    HGP2    0.330 !    0.000
ATOM H05    HGA3    0.090 !    0.000
ATOM H06    HGP2    0.330 !    0.000

BOND N    C   
BOND N    H02 
BOND N    H04 
BOND N    H06 
BOND C    H01 
BOND C    H03 
BOND C    H05 

END

read param card flex append
* Parameters generated by analogy by
* CHARMM General Force Field (CGenFF) program version 1.0.0
*

! Penalties lower than 10 indicate the analogy is fair; penalties between 10
! and 50 mean some basic validation is recommended; penalties higher than
! 50 indicate poor analogy and mandate extensive validation/optimization.

BONDS
CG334  NG3P3   200.00     1.4800 ! PROT new stretch and bend; methylammonium (KK 03/10/92)
CG334  HGA3    322.00     1.1110 ! PROT alkane update, adm jr., 3/2/92
NG3P3  HGP2    403.00     1.0400 ! PROT new stretch and bend; methylammonium (KK 03/10/92)

ANGLES
NG3P3  CG334  HGA3     45.00    107.50   35.00   2.10100 ! PROT methylammonium (KK 03/10/92)
HGA3   CG334  HGA3     35.50    108.40    5.40   1.80200 ! PROT alkane update, adm jr., 3/2/92
CG334  NG3P3  HGP2     30.00    109.50   20.00   2.07400 ! PROT new stretch and bend; methylammonium (KK 03/10/92)
HGP2   NG3P3  HGP2     44.00    109.50 ! PROT new stretch and bend; methylammonium (KK 03/10/92)

DIHEDRALS
HGA3   CG334  NG3P3  HGP2       0.0900  3     0.00 ! PROT fine-tuned to ab initio; METHYLAMMONIUM, KK 03/10/92

IMPROPERS

END
RETURN
```

**Comment by stefdoerr** [comment]
Can you please post the builder log file here? `/home/student1/avarela/DRUGG/acetate_adaptative_sampling/docked/build/1/log.txt`

Also the command you used to build.

**Comment by nesilin** [comment]
Sure! I forgott to do it...
log.txt file:
```
psfgen) clearing structure, topology, and aliases
psfgen) reading topology file 0.top_all22star_prot.rtf

psfgen) >>>>>>>>CHARMM22 All-Hydrogen Topology File for Proteins <<<<<<
psfgen) >>>>> Includes phi, psi cross term map (CMAP) correction <<<<<<<
psfgen) >>>>>>>>>>>>>>>>>>>>>> December, 2003 <<<<<<<<<<<<<<<<<<<<<<<<<<
psfgen)  All comments to ADM jr. via the CHARMM web site: www.charmm.org
psfgen)                parameter set discussion forum
psfgen) 
psfgen) Created by CHARMM version 31 1
psfgen) cross-term entries present in topology definitions
psfgen) reading topology file 1.top_water_ions.rtf

psfgen)  Topology for water and ions
psfgen) 
psfgen) Created by CHARMM version 31 1
psfgen) duplicate type key HT
psfgen) duplicate type key OT
psfgen) duplicate type key SOD
psfgen) duplicate type key MG
psfgen) duplicate type key POT
psfgen) duplicate type key CAL
psfgen) duplicate type key CES
psfgen) duplicate type key ZN
psfgen) duplicate type key CLA
psfgen) duplicate residue key TIP3 will be ignored
psfgen) duplicate residue key TP3M will be ignored
psfgen) duplicate residue key SOD will be ignored
psfgen) duplicate residue key MG will be ignored
psfgen) duplicate residue key POT will be ignored
psfgen) duplicate residue key CAL will be ignored
psfgen) duplicate residue key CES will be ignored
psfgen) duplicate residue key ZN2 will be ignored
psfgen) duplicate residue key CLA will be ignored
psfgen) reading topology file 2.top_nme_h.rtf

psfgen)  Topologies generated by
psfgen)  CHARMM General Force Field (CGenFF) program version 1.0.0
psfgen) 
psfgen) Created by CHARMM version 36 1
psfgen) reading topology file 3.top_all36_prot_arg0.rtf

psfgen)  Topology for protein related model compounds
psfgen) 
psfgen) Created by CHARMM version 31 1
psfgen) aliasing residue G to GUA
psfgen) aliasing residue C to CYT
psfgen) aliasing residue A to ADE
psfgen) aliasing residue T to THY
psfgen) aliasing residue U to URA
psfgen) aliasing residue GUA atom O5* to O5'
psfgen) aliasing residue GUA atom C5* to C5'
psfgen) aliasing residue GUA atom O4* to O4'
psfgen) aliasing residue GUA atom C4* to C4'
psfgen) aliasing residue GUA atom C3* to C3'
psfgen) aliasing residue GUA atom O3* to O3'
psfgen) aliasing residue GUA atom C2* to C2'
psfgen) aliasing residue GUA atom O2* to O2'
psfgen) aliasing residue GUA atom C1* to C1'
psfgen) aliasing residue CYT atom O5* to O5'
psfgen) aliasing residue CYT atom C5* to C5'
psfgen) aliasing residue CYT atom O4* to O4'
psfgen) aliasing residue CYT atom C4* to C4'
psfgen) aliasing residue CYT atom C3* to C3'
psfgen) aliasing residue CYT atom O3* to O3'
psfgen) aliasing residue CYT atom C2* to C2'
psfgen) aliasing residue CYT atom O2* to O2'
psfgen) aliasing residue CYT atom C1* to C1'
psfgen) aliasing residue ADE atom O5* to O5'
psfgen) aliasing residue ADE atom C5* to C5'
psfgen) aliasing residue ADE atom O4* to O4'
psfgen) aliasing residue ADE atom C4* to C4'
psfgen) aliasing residue ADE atom C3* to C3'
psfgen) aliasing residue ADE atom O3* to O3'
psfgen) aliasing residue ADE atom C2* to C2'
psfgen) aliasing residue ADE atom O2* to O2'
psfgen) aliasing residue ADE atom C1* to C1'
psfgen) aliasing residue THY atom O5* to O5'
psfgen) aliasing residue THY atom C5* to C5'
psfgen) aliasing residue THY atom O4* to O4'
psfgen) aliasing residue THY atom C4* to C4'
psfgen) aliasing residue THY atom C3* to C3'
psfgen) aliasing residue THY atom O3* to O3'
psfgen) aliasing residue THY atom C2* to C2'
psfgen) aliasing residue THY atom O2* to O2'
psfgen) aliasing residue THY atom C1* to C1'
psfgen) aliasing residue URA atom O5* to O5'
psfgen) aliasing residue URA atom C5* to C5'
psfgen) aliasing residue URA atom O4* to O4'
psfgen) aliasing residue URA atom C4* to C4'
psfgen) aliasing residue URA atom C3* to C3'
psfgen) aliasing residue URA atom O3* to O3'
psfgen) aliasing residue URA atom C2* to C2'
psfgen) aliasing residue URA atom O2* to O2'
psfgen) aliasing residue URA atom C1* to C1'
psfgen) aliasing residue ILE atom CD1 to CD
psfgen) aliasing residue SER atom HG to HG1
psfgen) aliasing residue HIS to HSD
psfgen) aliasing residue HEM to HEME
psfgen) aliasing residue HEME atom N A to NA
psfgen) aliasing residue HEME atom N B to NB
psfgen) aliasing residue HEME atom N C to NC
psfgen) aliasing residue HEME atom N D to ND
psfgen) aliasing residue HOH to TIP3
psfgen) aliasing residue TIP3 atom O to OH2
psfgen) aliasing residue K to POT
psfgen) aliasing residue K atom K to POT
psfgen) aliasing residue ICL to CLA
psfgen) aliasing residue ICL atom CL to CLA
psfgen) aliasing residue INA to SOD
psfgen) aliasing residue INA atom NA to SOD
psfgen) aliasing residue CA to CAL
psfgen) aliasing residue CA atom CA to CAL
psfgen) aliasing residue ZN to ZN2
psfgen) aliasing residue LYS atom 1HZ to HZ1
psfgen) aliasing residue LYS atom 2HZ to HZ2
psfgen) aliasing residue LYS atom 3HZ to HZ3
psfgen) aliasing residue ARG atom 1HH1 to HH11
psfgen) aliasing residue ARG atom 2HH1 to HH12
psfgen) aliasing residue ARG atom 1HH2 to HH21
psfgen) aliasing residue ARG atom 2HH2 to HH22
psfgen) aliasing residue ASN atom 1HD2 to HD21
psfgen) aliasing residue ASN atom 2HD2 to HD22
psfgen) aliasing residue LI to LIT
psfgen) aliasing residue NA to SOD
psfgen) aliasing residue K to POT
psfgen) aliasing residue CA to CAL
psfgen) aliasing residue ZN to ZN2
psfgen) aliasing residue CL to CLA
psfgen) aliasing residue RB to RUB
psfgen) aliasing residue CD to CD2
psfgen) aliasing residue CS to CES
psfgen) aliasing residue BA to BAR
psfgen) aliasing residue AR0 to ARG
psfgen) aliasing residue GLH to GLU
psfgen) aliasing residue ASH to ASP
psfgen) aliasing residue LYN to LYS
psfgen) aliasing residue HIE to HSE
psfgen) aliasing residue HID to HSD
psfgen) aliasing residue HIP to HSP
psfgen) aliasing residue CYX to CYS
psfgen) aliasing residue WAT to TIP3
psfgen) aliasing residue ALA atom H to HN
psfgen) aliasing residue ARG atom H to HN
psfgen) aliasing residue ARG atom HB3 to HB1
psfgen) aliasing residue ARG atom HG3 to HG1
psfgen) aliasing residue ARG atom HD3 to HD1
psfgen) aliasing residue ASP atom H to HN
psfgen) aliasing residue ASP atom HB3 to HB1
psfgen) aliasing residue ASN atom H to HN
psfgen) aliasing residue ASN atom HB3 to HB1
psfgen) aliasing residue CYS atom H to HN
psfgen) aliasing residue CYS atom HB3 to HB1
psfgen) aliasing residue GLU atom H to HN
psfgen) aliasing residue GLU atom HB3 to HB1
psfgen) aliasing residue GLU atom HG3 to HG1
psfgen) aliasing residue GLN atom H to HN
psfgen) aliasing residue GLN atom HB3 to HB1
psfgen) aliasing residue GLN atom HG3 to HG1
psfgen) aliasing residue GLY atom H to HN
psfgen) aliasing residue GLY atom HA3 to HA1
psfgen) aliasing residue HIS atom H to HN
psfgen) aliasing residue HIS atom HB3 to HB1
psfgen) aliasing residue ILE atom H to HN
psfgen) aliasing residue ILE atom HG13 to HG11
psfgen) aliasing residue ILE atom HD11 to HD1
psfgen) aliasing residue ILE atom HD12 to HD2
psfgen) aliasing residue ILE atom HD13 to HD3
psfgen) aliasing residue LEU atom H to HN
psfgen) aliasing residue LEU atom HB3 to HB1
psfgen) aliasing residue LYS atom H to HN
psfgen) aliasing residue LYS atom HB3 to HB1
psfgen) aliasing residue LYS atom HG3 to HG1
psfgen) aliasing residue LYS atom HD3 to HD1
psfgen) aliasing residue LYS atom HE3 to HE1
psfgen) aliasing residue MET atom H to HN
psfgen) aliasing residue MET atom HB3 to HB1
psfgen) aliasing residue MET atom HG3 to HG1
psfgen) aliasing residue PHE atom H to HN
psfgen) aliasing residue PHE atom HB3 to HB1
psfgen) aliasing residue PRO atom H2 to HT2
psfgen) aliasing residue PRO atom H3 to HT1
psfgen) aliasing residue PRO atom HB3 to HB1
psfgen) aliasing residue PRO atom HG3 to HG1
psfgen) aliasing residue PRO atom HD3 to HD1
psfgen) aliasing residue SER atom H to HN
psfgen) aliasing residue SER atom HB3 to HB1
psfgen) aliasing residue THR atom H to HN
psfgen) aliasing residue TRP atom H to HN
psfgen) aliasing residue TRP atom HB3 to HB1
psfgen) aliasing residue TYR atom H to HN
psfgen) aliasing residue TYR atom HB3 to HB1
psfgen) aliasing residue VAL atom H to HN
psfgen) building segment P
psfgen) reading residues from pdb file segmentP.pdb
psfgen) extracted 223 residues from pdb file
psfgen) setting patch for first residue to ACE
psfgen) setting patch for last residue to CT3
psfgen) Info: generating structure...psfgen) Info: skipping improper N-C-CA-HN at beginning of segment.
psfgen) Info: skipping conformation C-N-CA-C at beginning of segment.
psfgen) Info: skipping conformation C-CA-N-HN at beginning of segment.
psfgen) Info: skipping bond C-N at end of segment.
psfgen) Info: skipping improper C-CA-N-O at end of segment.
psfgen) Info: skipping conformation CA-C-N-CA at end of segment.
psfgen) Info: skipping conformation N-CA-C-O at end of segment.
psfgen) Info: skipping conformation N-CA-C-N at end of segment.
segment complete.
psfgen) reading coordinates from pdb file segmentP.pdb for segment P
psfgen) Warning: failed to set coordinate for atom OXT	 ASN:245	  P
psfgen) building segment CA
psfgen) reading residues from pdb file segmentCA.pdb
psfgen) extracted 1 residues from pdb file
psfgen) setting patch for first residue to NONE
psfgen) setting patch for last residue to NONE
psfgen) Info: generating structure...segment complete.
psfgen) reading coordinates from pdb file segmentCA.pdb for segment CA
psfgen) building segment W
psfgen) disabling angle autogeneration
psfgen) disabling dihedral autogeneration
psfgen) reading residues from pdb file segmentW.pdb
psfgen) extracted 62 residues from pdb file
psfgen) setting patch for first residue to NONE
psfgen) setting patch for last residue to NONE
psfgen) Info: generating structure...segment complete.
psfgen) reading coordinates from pdb file segmentW.pdb for segment W
psfgen) building segment L
psfgen) reading residues from pdb file segmentL.pdb
psfgen) unknown residue type MOL
psfgen) extracted 1 residues from pdb file
psfgen) setting patch for first residue to NONE
psfgen) setting patch for last residue to NONE
psfgen) Info: generating structure...psfgen) unknown residue type MOL
failed!
P:245 
P:16 
```

**Comment by stefdoerr** [comment]
Yes, see the last error in the log:
```
psfgen) Info: generating structure...psfgen) unknown residue type MOL
failed!
```
Your problem is that you call your ligand MOL (as it's resname) but then you don't use that name in the parameter and topology files.

Check the tutorial files for BenTryp:

```
RESI MOL  1.000
GROUP
```

while yours says
```
RESI /scrat
GROUP
```

Of course then the forcefield cannot find parameters for the residue MOL since you defined parameters for a residue called /scrat

**Comment by nesilin** [comment]
Thanks for answering!
But I do not understand why we have been able to built the system with the bezamidine  and the ethanol with the parametrization files provided in the tutorials but we haven't been able to built the system with the methylamine with the parametrization files provided by CGenFF... The point is that it seems that the rtf and the prm files are the problem. The script we run is very similar to the one in the tutorial 'Using docking to initialize positions'. 
Here is part of the code:
```
from htmd import *
from htmd.molecule.util import maxDistance
from htmd.protocols.equilibration_v1 import Equilibration
from htmd.protocols.production_v1 import Production
from natsort import natsorted

# Using docking to generate starting poses for simulations
# Dock the protein with the ligand

prot = Molecule('nmetryp/trypsin.pdb')
prot.filter('chain A and (protein or water or resname CA)')
prot.set('segid', 'P', sel='protein and noh')
prot.set('segid', 'W', sel='water')
prot.set('segid', 'CA', sel='resname CA')
D = maxDistance(prot, 'all')
D = D + 15
prot.center()
lig = Molecule('nmetryp/nme_h.pdb')
print(lig,prot)
poses, scores = dock(prot, lig)

# Build systems from docked poses
print ("Building systems from docked poses...")
moltbuilt=[]
for i, p in enumerate(poses):
    ligand = p
    ligand.set('segid','L')
    ligand.set('resname','MOL')

    mol = Molecule(name='combo')
    mol.append(prot)
    mol.append(ligand)

    smol = solvate(mol, minmax=[[-D, -D, -D], [D, D, D]])
    topos  = ['top/top_all22star_prot.rtf', 'top/top_water_ions.rtf', './nmetryp/top_nme_h.rtf']
    params = ['par/par_all22star_prot.prm', 'par/par_water_ions.prm', './nmetryp/par_nme_h.prm']

    moltbuilt.append(charmm.build(smol, topo=topos, param=params, outdir='./docked/build/{}/'.format(i+1), saltconc=0.15))
    if i==4: # For time purposes lets only build the two first
        break
```

**Comment by stefdoerr** [comment]
Simply because the `rtf` file that CGenFF spits out doesn't respect your residue naming.

**Comment by stefdoerr** [comment]
Your code is probably fine. It's just the naming in the `rtf` file that is wrong, so obviously the tutorial files work and yours don't.

**Comment by j3mdamas** [comment]
Inés,
It's what Stefan is saying. The .rtf and .prm files we provided in the tutorials are already prepared for a ligand named "MOL". So, when we go `ligand.set('resname','MOL')`, it's already with that in mind.

Change `/scrat` to `MOL`, as Stefan suggested.

**Comment by nesilin** [comment]
You're right! Now I see it. Thank you both!

**Comment by j3mdamas** [comment]
This has other issues Stefan, sorry

**Comment by j3mdamas** [comment]
Basically parameterize does not detect torsions on ACE or NME. I'm going to change the title of the issue.

**Comment by j3mdamas** [comment]
@mj-harvey, let's discuss this tomorrow. I'm not sure why these torsions aren't being recognized by parameterize.

**Comment by mj-harvey** [comment]
Send me mol/pdbs would you, please?

**Comment by j3mdamas** [comment]
```
@<TRIPOS>MOLECULE
nme_h.pdb
 8 7 0 0 0
SMALL
GASTEIGER

@<TRIPOS>ATOM
      1  N         25.1930   13.0570   24.1750 N.4     1  NME1        0.2163
      2  C         26.3230   12.9170   25.1300 C.3     1  NME1       -0.0466
      3  H01       26.6650   11.8820   25.1390 H       1  NME1        0.0776
      4  H02       24.8740   12.1410   23.8930 H       1  NME1        0.1991
      5  H03       25.9920   13.2000   26.1290 H       1  NME1        0.0776
      6  H04       25.5000   13.5720   23.3620 H       1  NME1        0.1991
      7  H05       27.1420   13.5670   24.8210 H       1  NME1        0.0776
      8  H06       24.4350   13.5540   24.6210 H       1  NME1        0.1991
@<TRIPOS>BOND
     1     1     2    1
     2     1     4    1
     3     1     6    1
     4     1     8    1
     5     2     3    1
     6     2     5    1
     7     2     7    1
```
Here's an example, NME (just paste it into a .mol2 file). These are very simple molecules, with just one torsion, but unlike ethanol, `parameterize` does not seem to identify the torsion.

**Comment by mj-harvey** [comment]
Parameterise excludes methyl groups, on the grounds that they're probably
already well parameterised. Unfortunately, if that leaves no soft
dihedrals, then I think it won't even try to do the charge fitting.

M

On 20 June 2016 at 20:43, João M. Damas <notifications@github.com> wrote:

> @<TRIPOS>MOLECULE
> nme_h.pdb
>  8 7 0 0 0
> SMALL
> GASTEIGER
>
> @<TRIPOS>ATOM
>       1  N         25.1930   13.0570   24.1750 N.4     1  NME1        0.2163
>       2  C         26.3230   12.9170   25.1300 C.3     1  NME1       -0.0466
>       3  H01       26.6650   11.8820   25.1390 H       1  NME1        0.0776
>       4  H02       24.8740   12.1410   23.8930 H       1  NME1        0.1991
>       5  H03       25.9920   13.2000   26.1290 H       1  NME1        0.0776
>       6  H04       25.5000   13.5720   23.3620 H       1  NME1        0.1991
>       7  H05       27.1420   13.5670   24.8210 H       1  NME1        0.0776
>       8  H06       24.4350   13.5540   24.6210 H       1  NME1        0.1991
> @<TRIPOS>BOND
>      1     1     2    1
>      2     1     4    1
>      3     1     6    1
>      4     1     8    1
>      5     2     3    1
>      6     2     5    1
>      7     2     7    1
>
> Here's an example, NME (just paste it into a .mol2 file). These are very
> simple molecules, with just one torsion, but unlike ethanol, parameterize
> does not seem to identify the torsion.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/61#issuecomment-227247708>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHh-DdpZChAHpvyAHHUndgGVPlsbKv7lks5qNu1OgaJpZM4I1JT4>
> .
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by j3mdamas** [comment]
It should at least then output the guess it made, and make the charge fitting.

**Comment by mj-harvey** [comment]
The next version of parameterise will do charge fitting even if there are no soft dihedrals.
