### ISSUE TITLE
HTMD executable

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/htmd#650]
I accidentally misstyped (I wanted to cd)
```pytb
[sdoerr@loro Sun13:03 Work] htmd
Traceback (most recent call last):
  File "/shared/sdoerr/Software/miniconda3/bin/htmd", line 11, in <module>
    sys.exit(main_htmd())
  File "/shared/sdoerr/Work/htmd/htmdx/cli.py", line 249, in main_htmd
    import qtconsole.qtconsoleapp
ModuleNotFoundError: No module named 'qtconsole'
```
Are we supposed to still have that executable lying around? Can we remove it?

**Comment by j3mdamas** [comment]
htmdx refactoring is undergoing. it will be cleaned by then. right now, it does not hurt anybody.
