### ISSUE TITLE
joblib 0.12 bug

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#734]
With joblib 0.12, we're having this bug on `delayed` calls in:

```
AssertionError: Tests failed for the following files:
/home/joao/maindisk/SANDBOX/acemanager/latest_2018-07-05_20h16/lib/python3.6/site-packages/htmd/adaptive/adaptivegoal.py
/home/joao/maindisk/SANDBOX/acemanager/latest_2018-07-05_20h16/lib/python3.6/site-packages/htmd/adaptive/adaptivegoaleg.py
/home/joao/maindisk/SANDBOX/acemanager/latest_2018-07-05_20h16/lib/python3.6/site-packages/htmd/projections/metricrmsd.py
/home/joao/maindisk/SANDBOX/acemanager/latest_2018-07-05_20h16/lib/python3.6/site-packages/htmd/projections/metrictmscore.py
```

Trace details on `metricrmsd.py`.

```python
[joao@computer02 htmd]$ python htmd/projections/metricrmsd.py 
/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/site-packages/htmd/molecule/readers.py:778: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  serials = parsedtopo.serial.as_matrix()
Creating simlist: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1795.89it/s]
2018-07-06 12:16:46,713 - htmd.molecule.readers - WARNING - Integer values detected in "insertion" field. Your resids might be overflowing. Take care
/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/site-packages/htmd/molecule/readers.py:778: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  serials = parsedtopo.serial.as_matrix()
2018-07-06 12:16:50,822 - htmd.molecule.readers - WARNING - Integer values detected in "insertion" field. Your resids might be overflowing. Take care
Projecting trajectories: 100%|██████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  5.22it/s]
Traceback (most recent call last):
  File "/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 377, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MetricRmsd' on <module 'joblib.externals.loky.backend.popen_loky_posix' from '/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/site-packages/joblib/externals/loky/backend/popen_loky_posix.py'>
Traceback (most recent call last):
  File "/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 377, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'MetricRmsd' on <module 'joblib.externals.loky.backend.popen_loky_posix' from '/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/site-packages/joblib/externals/loky/backend/popen_loky_posix.py'>
Traceback (most recent call last):
  File "htmd/projections/metricrmsd.py", line 161, in <module>
    data2 = metr2.project()
  File "/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/site-packages/htmd/projections/metric.py", line 143, in project
    results = aprun(total=numSim, desc='Projecting trajectories')(delayed(_processSim)(self.simulations[i], self.projectionlist, uqMol, self.skip) for i in range(numSim))
  File "/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/site-packages/htmd/parallelprogress.py", line 18, in <lambda>
    return lambda x: Parallel(**joblib_args)(tqdm_f(x, tq_args))
  File "/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/site-packages/joblib/parallel.py", line 962, in __call__
    self.retrieve()
  File "/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/site-packages/joblib/parallel.py", line 865, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 515, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/site-packages/joblib/externals/loky/_base.py", line 431, in result
    return self.__get_result()
  File "/home/joao/maindisk/SANDBOX/acemanager/latest/lib/python3.6/site-packages/joblib/externals/loky/_base.py", line 382, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A process in the executor was terminated abruptly while the future was running or pending.
```

I see there's an issue open on joblib repo related with this: https://github.com/joblib/joblib/issues/643, I'm going to ping them, to see if it's fixable, but it's out of our realm of expertise. For now, I'll pin joblib to 0.11 (which works) and re-release HTMD.

Note: the worst of all, is that it does not fail on Travis (even though 0.12 is intalled there). @stefdoerr and I found out why for the adaptive fails, but we don't understand for the metric fails.

**Comment by j3mdamas** [comment]
This is fixed in joblib 1.12.2 (tested). It's already in conda-forge, but not in standard anaconda channel. As soon as it comes to standard, I'll remove the version pinning and close this issue.
