### ISSUE TITLE
Error during ligand parameterization

### ISSUE THREAD

**Issue by oliverfleetwood** [Acellera/htmd#760]
Hi,

I am trying to parameterize a protonated ligand for charmm on a 64 core node with the command `parameterize {ligand}.mol2 --charge 1 -ff CGENFF --ncpu 64`.

I get the following error after the computing the electrostatic potential (both the first time and during a rerun):

2018-08-23 09:57:03,368 - htmd.parameterization.cli - INFO - Overriding ncpus to 64
2018-08-23 09:57:04,269 - htmd.parameterization.util - INFO - Rename segment to L
2018-08-23 09:57:04,269 - htmd.parameterization.util - INFO - Rename residue to MOL
2018-08-23 09:57:04,269 - htmd.parameterization.util - INFO - Rename atom 0: C    --> C1  
2018-08-23 09:57:04,269 - htmd.parameterization.util - INFO - Rename atom 1: C    --> C2  
...
...
2018-08-23 09:57:17,533 - htmd.parameterization.fftype - INFO - Assigned atom types with CGenFF_2b6
2018-08-23 09:57:29,879 - htmd.parameterization.util - INFO - Reusing ESP grid from ./esp/B3LYP-cc-pVDZ-vacuum/00000/grid.dat
2018-08-23 09:57:30,001 - htmd.parameterization.esp - INFO - Start charge optimization
2018-08-23 09:59:22,046 - htmd.parameterization.esp - INFO - Final RMSD: 0.125998 au
2018-08-23 09:59:22,047 - htmd.parameterization.esp - INFO - Finish charge optimization
2018-08-23 09:59:22,048 - htmd.parameterization.util - INFO - Set charge C1: -0.243
2018-08-23 09:59:22,048 - htmd.parameterization.util - INFO - Set charge C2:  0.032
...
...
Traceback (most recent call last):
  File "/nethome/oliverfl/anaconda2/envs/py3/bin/parameterize", line 11, in <module>
    sys.exit(main_parameterize())
  File "/nethome/oliverfl/anaconda2/envs/py3/lib/python3.6/site-packages/htmd/parameterization/cli.py", line 267, in main_parameterize
    logger.info('QM dipole: %f %f %f; %f' % tuple(qm_dipole))
TypeError: 'NoneType' object is not iterable

Looking at the code, I guess it means that `qm_dipole` returned by `fitCharges` is None. 
Any ideas on what goes wrong? 
Best

**Comment by stefdoerr** [comment]
Indeed. Could you provide the ligand so that I can debug it fast? Thanks!

**Comment by oliverfleetwood** [comment]
Sure, here it is!
[p0g_export_github_acellera.zip](https://github.com/Acellera/htmd/files/2313652/p0g_export_github_acellera.zip)

**Comment by j3mdamas** [comment]
@oliverfleetwood can you tell us which version of htmd are you using? `conda list htmd` should suffice

**Comment by stefdoerr** [comment]
I can reproduce it on master. Debugging it right now

**Comment by stefdoerr** [comment]
It's a bug related to PSI4 changing it's output files and us thus not parsing them correctly anymore. I'll have a fix ready soon.

**Comment by oliverfleetwood** [comment]
ok great! Thanks for your quick help

**Comment by stefdoerr** [comment]
Hey @oliverfleetwood . The bug is fixed now on the `master` branch. You can either use the git version or wait for the next official release of HTMD
