### ISSUE TITLE
No terminal caps

### ISSUE THREAD

**Issue by andt88** [Acellera/htmd#763]
I am trying to build a protein without terminal caps. I run:

```
caps = {'protein': ['none', 'none']}
bmol_amber = amber.build(smol, ff=['leaprc.gaff2', 'leaprc.water.tip3p', 'leaprc.protein.ff14SB'], ionize=True, topo=topos_amber, param=frcmods_amber, disulfide=disu, saltconc=0.05,  caps = caps, outdir='./build_amber_{}'.format(i))
```
which gives me the following error:

> Traceback (most recent call last):
>   File "built_system.py", line 62, in <module>
>     bmol_amber = amber.build(smol, ff=['leaprc.gaff2', 'leaprc.water.tip3p', 'leaprc.protein.ff14SB'], ionize=True, topo=topos_amber, param=frcmods_amber, disulfide=disu, saltconc=0.05,  caps = caps, outdir='./build_amber_{}'.format(i))
>   File "/home/andy/anaconda3/lib/python3.5/site-packages/htmd/builder/amber.py", line 263, in build
>     _applyProteinCaps(mol, caps)
>   File "/home/andy/anaconda3/lib/python3.5/site-packages/htmd/builder/amber.py", line 486, in _applyProteinCaps
>     raise RuntimeError('There is no segment {} in the molecule.'.format(seg))
> RuntimeError: There is no segment protein in the molecule.
>

**Comment by stefdoerr** [comment]
You need to assign a segment ID to your protein and use that.

```python
smol.set('segid', 'P', sel='protein')
caps = {'P': ['none', 'none']}
bmol_amber = amber.build(smol, ff=['leaprc.gaff2', 'leaprc.water.tip3p', 'leaprc.protein.ff14SB'], ionize=True, topo=topos_amber, param=frcmods_amber, disulfide=disu, saltconc=0.05,  caps = caps, outdir='./build_amber_{}'.format(i))
```

This should work

**Comment by stefdoerr** [comment]
Or to find out the current segment IDs just `print(smol.segid)`
