### ISSUE TITLE
autoSegment error

### ISSUE THREAD

**Issue by andt88** [Acellera/htmd#769]
When running

```
from htmd.ui import *
from htmd.home import home
from os.path import join
import os as os
from htmd.molecule.util import maxDistance
config(viewer='vmd')
datadir = os.getcwd()


prot = Molecule(join(datadir, 'prot.pdb'))
prot = proteinPrepare(prot, pH=7.0, returnDetails=True)
prot = autoSegment(prot, sel='protein')Traceback (most recent call last):
```

I get this error:
```

  File "built_system.py", line 11, in <module>
    prot = autoSegment(prot, sel='protein')
  File "/home/andt88/miniconda2/envs/py36/lib/python3.6/site-packages/htmd/builder/builder.py", line 261, in autoSegment
    mol = mol.copy()
AttributeError: 'tuple' object has no attribute 'copy'
```

**Comment by j3mdamas** [comment]
When using `returnDetails=True`, the return are two objects (a Molecule and a DataFrame). As such, please use:
```python
prot, details = proteinPrepare(prot, pH=7.0, returnDetails=True)
```
João
