### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by andt88** [Acellera/htmd#772]
When trying to save my model with the below code I run into a memory problem.

```
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from htmd.ui import *
from pylab import *
from htmd.config import config
config(viewer='vmd', ncpus=1)

...

print('Calculating implied time scales')
model = Model(dataBoot)
model.save('model0')
model.plotTimescales(minlag=1.0, maxlag=50.0, units='ns', plot=False, save='its.png')
model.save('model1')
print('Generate Markov Model')
model.markovModel(10, 6, units='ns')
model.save('model2')

...
```

This is the error I get:

```

estimating MaximumLikelihoodMSM: 100% (26/26) [####################] eta 00:01 \Traceback (most recent call last):
  File "htmd_dG.py", line 43, in <module>
    model.save('model1')
  File "/home/local/andtos-loc/anaconda3/lib/python3.5/site-packages/htmd/model.py", line 691, in save
    pickle.dump(self.__dict__, f)
MemoryError

```

**Comment by stefdoerr** [comment]
yeah I think I remember that it copies everything so it practically doubles your memory usage when pickling the models.
if you really want to you can delete the projections from inside the data of the model, thus saving just the model and the states, but then you might not be able to calculate stuff like average contact maps etc. later.
If you want to do that, do
```python
for traj in model.data.trajectories:
   traj._projection = []
```
This should free up lots of memory.

**Comment by andt88** [comment]
With my trajectory growing larger, I an into this new memory issue when doing the featurization:

```
data = metr.project()
2018-09-17 21:53:20,950 - htmd.molecule.readers - WARNING - Atoms with names "HG11" "HG12" "HG13" "HG21" "HG22" "HG23" were guessed as element H but could also be Hg (mercury). If this is a case, you can correct them with mol.set('element', 'Hg', sel='name "HG11" "HG12" "HG13" "HG21" "HG22" "HG23"')
2018-09-17 21:53:20,951 - htmd.molecule.readers - WARNING - Atoms with names "HE21" "HE22" were guessed as element H but could also be He (helium). If this is a case, you can correct them with mol.set('element', 'He', sel='name "HE21" "HE22"')
/home/local/andtos-loc/anaconda3/lib/python3.5/site-packages/htmd/molecule/readers.py:200: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(mol._dtypes[field], np.float) \
/home/local/andtos-loc/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)
Projecting trajectories: .../24 [16:20<00:00, 40.84s/it]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/local/andtos-loc/anaconda3/lib/python3.5/site-packages/htmd/projections/metric.py", line 141, in project
    results = aprun(total=numSim, desc='Projecting trajectories')(delayed(_processSim)(self.simulations[i], self.projectionlist, uqMol, self.skip) for i in range(numSim))
  File "/home/local/andtos-loc/anaconda3/lib/python3.5/site-packages/htmd/parallelprogress.py", line 18, in <lambda>
    return lambda x: Parallel(**joblib_args)(tqdm_f(x, tq_args))
  File "/home/local/andtos-loc/anaconda3/lib/python3.5/site-packages/joblib/parallel.py", line 996, in __call__
    self.retrieve()
  File "/home/local/andtos-loc/anaconda3/lib/python3.5/site-packages/joblib/parallel.py", line 899, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/local/andtos-loc/anaconda3/lib/python3.5/site-packages/joblib/_parallel_backends.py", line 517, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/local/andtos-loc/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/home/local/andtos-loc/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

```

**Comment by stefdoerr** [comment]
By the way did this help? can we close the issue?

**Comment by andt88** [comment]
> @andt88 we received a notification for a message from 14 hours ago where you still faced memory issues, but that message seems to be gone. Were the issues solved? Did you follow @stefdoerr's suggestion?

This was another issue which I solved by setting ncpus=1, as described elsewhere.

**Comment by andt88** [comment]
> By the way did this help? can we close the issue?
Right now what I'm doing instead of saving is leaving the python terminal running so I can try different parameters on the dataset. I have not tried your solution yet as I'm stuck on the box size issue.

**Comment by j3mdamas** [comment]
I think we can close this. @andt88, if you are still facing issues, let us know.
