### ISSUE TITLE
Molecule doctest failures are ignored on Travis

### ISSUE THREAD

**Issue by raimis** [Acellera/htmd#820]
The code in `molecule.py` doesn't catch failing doctests:
```python
if __name__ == "__main__":
    # Unfortunately, tests affect each other because only a shallow copy is done before each test, so
    # I do a 'copy' before each.
    import doctest
    import unittest

    m = Molecule('3PTB')
    doctest.testmod(extraglobs={'tryp': m.copy()})

    unittest.main(verbosity=2)
```

Failing tests:
```
**********************************************************************
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/site-packages/htmd/molecule/molecule.py", line 565, in __main__.Molecule.append
Failed example:
mol.filter("not resname BEN")
Expected nothing
Got:
array([1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638], dtype=int32)
**********************************************************************
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/site-packages/htmd/molecule/molecule.py", line 567, in __main__.Molecule.append
Failed example:
lig.filter("resname BEN")
Expected nothing
Got:
array([   0,    1,    2, ..., 1698, 1699, 1700], dtype=int32)
**********************************************************************
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/site-packages/htmd/molecule/molecule.py", line 1408, in __main__.Molecule.dropFrames
Failed example:
mol.numFrames == 2
Expected nothing
Got:
True
**********************************************************************
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/site-packages/htmd/molecule/molecule.py", line 1410, in __main__.Molecule.dropFrames
Failed example:
mol.numFrames == 1
Expected nothing
Got:
True
**********************************************************************
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/site-packages/htmd/molecule/molecule.py", line 662, in __main__.Molecule.filter
Failed example:
mol.filter('protein')
Expected nothing
Got:
array([1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639,
1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650,
1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661,
1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672,
1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683,
1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694,
1695, 1696, 1697, 1698, 1699, 1700], dtype=int32)
**********************************************************************
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/site-packages/htmd/molecule/molecule.py", line 792, in __main__.Molecule.getDihedral
Failed example:
mol.getDihedral([0, 5, 8, 12])
Exception raised:
Traceback (most recent call last):
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/doctest.py", line 1330, in __run
compileflags, 1), test.globs)
File "<doctest __main__.Molecule.getDihedral[0]>", line 1, in <module>
mol.getDihedral([0, 5, 8, 12])
NameError: name 'mol' is not defined
**********************************************************************
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/site-packages/htmd/molecule/molecule.py", line 1513, in __main__.Molecule.renumberResidues
Failed example:
mapping = mol.renumberResidues(returnMapping=True)
Exception raised:
Traceback (most recent call last):
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/doctest.py", line 1330, in __run
compileflags, 1), test.globs)
File "<doctest __main__.Molecule.renumberResidues[0]>", line 1, in <module>
mapping = mol.renumberResidues(returnMapping=True)
NameError: name 'mol' is not defined
**********************************************************************
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/site-packages/htmd/molecule/molecule.py", line 812, in __main__.Molecule.setDihedral
Failed example:
mol.setDihedral([0, 5, 8, 12], 0.16)
Exception raised:
Traceback (most recent call last):
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/doctest.py", line 1330, in __run
compileflags, 1), test.globs)
File "<doctest __main__.Molecule.setDihedral[0]>", line 1, in <module>
mol.setDihedral([0, 5, 8, 12], 0.16)
NameError: name 'mol' is not defined
**********************************************************************
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/site-packages/htmd/molecule/molecule.py", line 814, in __main__.Molecule.setDihedral
Failed example:
bonds = mol._getBonds()
Exception raised:
Traceback (most recent call last):
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/doctest.py", line 1330, in __run
compileflags, 1), test.globs)
File "<doctest __main__.Molecule.setDihedral[1]>", line 1, in <module>
bonds = mol._getBonds()
NameError: name 'mol' is not defined
**********************************************************************
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/site-packages/htmd/molecule/molecule.py", line 815, in __main__.Molecule.setDihedral
Failed example:
mol.setDihedral([0, 5, 8, 12], 0.16, bonds=bonds)
Exception raised:
Traceback (most recent call last):
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/doctest.py", line 1330, in __run
compileflags, 1), test.globs)
File "<doctest __main__.Molecule.setDihedral[2]>", line 1, in <module>
mol.setDihedral([0, 5, 8, 12], 0.16, bonds=bonds)
NameError: name 'mol' is not defined
**********************************************************************
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/site-packages/htmd/molecule/molecule.py", line 816, in __main__.Molecule.setDihedral
Failed example:
mol.setDihedral([18, 20, 24, 30], -1.8, bonds=bonds)
Exception raised:
Traceback (most recent call last):
File "/home/travis/miniconda/envs/travis-env/lib/python3.6/doctest.py", line 1330, in __run
compileflags, 1), test.globs)
File "<doctest __main__.Molecule.setDihedral[3]>", line 1, in <module>
mol.setDihedral([18, 20, 24, 30], -1.8, bonds=bonds)
NameError: name 'mol' is not defined
**********************************************************************
6 items had failures:
2 of   5 in __main__.Molecule.append
2 of   5 in __main__.Molecule.dropFrames
1 of   2 in __main__.Molecule.filter
1 of   1 in __main__.Molecule.getDihedral
1 of   1 in __main__.Molecule.renumberResidues
4 of   4 in __main__.Molecule.setDihedral
***Test Failed*** 11 failures.
```

**Comment by stefdoerr** [comment]
Molecule has moved to moleculekit and I don't plan to support doctests. They are a mess to write and maintain. If there are strong objections reopen the issue on the moleculekit tracker.
