### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by ggutierrez-bio** [Acellera/htmd#88]
I've been running a parameterization for a while (several days) and now the output says:  

```
Running QM Calculations:  29% ( 43/147) [######################################                                                                                              ] eta 112:27:58 \Traceback (most recent call last):
  File "<string>", line 77, in <module>
  File "/data2/ggutierrez/anaconda3/envs/htmd/share/python/driver.py", line 1191, in optimize
    thisenergy = gradient(name, **kwargs)
  File "/data2/ggutierrez/anaconda3/envs/htmd/share/python/driver.py", line 762, in gradient
    procedures['gradient'][lowername](lowername, **kwargs)
  File "/data2/ggutierrez/anaconda3/envs/htmd/share/python/proc.py", line 1745, in run_scf_gradient
    run_scf(name, **kwargs)
  File "/data2/ggutierrez/anaconda3/envs/htmd/share/python/proc.py", line 1707, in run_scf
    scf_helper(name, **kwargs)
  File "/data2/ggutierrez/anaconda3/envs/htmd/share/python/proc.py", line 1933, in scf_helper
    e_scf = psi4.scf(precallback, postcallback)
RuntimeError:
Fatal Error: Iterations did not converge.
Error occurred in file: /export131/home/mjharvey/working/psi4public/src/lib/libparallel/process.cc on line: 193
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(psi::Options&, _object*, _object*)
 (/export131/home/mjharvey/working/psi4public/src/lib/libparallel/process.cc:193)
Segmentation fault (core dumped)
```

it didn't stop the parameterization, the program still runs (108/147, right now).
Is this expected to happen?
(it happened with many others besides 43/147)

**Comment by j3mdamas** [comment]
Hi @ggutierrez-bio,

Several QM calculations are performed scanning the dihedrals. That error just means that one of the calculations failed (at a specific dihedral). This may be due to several reasons, one could be that restricting that dihedral at that value may cause unavoidable molecular clashes. We will try to improve it in the future.

João

**Comment by j3mdamas** [comment]
Improve the error catching, I mean.
