### ISSUE TITLE
Parameterize: problem with the order of improper atoms for CHARMM

### ISSUE THREAD

**Issue by raimis** [Acellera/htmd#900]
Based on https://acellera.mojohelpdesk.com/ma/#/tickets/24462934, I have found a small molecule, which reproduces the problem.

```
$ cat acetoacetic_acid.mol2 
@<TRIPOS>MOLECULE
    UNL
   13    12     0     0     0
SMALL
USER_CHARGES


@<TRIPOS>ATOM
      1 C          -1.5922   -1.0789   -0.5292 C          1 UNL     -0.200100
      2 C0         -0.3402   -0.2046   -0.6243 C          1 UNL      0.578100
      3 O           0.0949    0.1523   -1.7052 O          1 UNL     -0.538100
      4 C1          0.2939    0.1670    0.7343 C          1 UNL     -0.296400
      5 C2          1.5632    1.0468    0.7665 C          1 UNL      0.637100
      6 O0          2.0592    1.4515   -0.4232 O          1 UNL     -0.576100
      7 O1          2.0992    1.3662    1.8110 O          1 UNL     -0.489000
      8 H          -1.9826   -1.2994   -1.5310 H          1 UNL      0.074367
      9 H0         -2.3696   -0.5625    0.0477 H          1 UNL      0.074367
     10 H1         -1.3542   -2.0246   -0.0263 H          1 UNL      0.074367
     11 H2         -0.4731    0.6750    1.3315 H          1 UNL      0.104700
     12 H3          0.5287   -0.7675    1.2585 H          1 UNL      0.104700
     13 H4          1.4726    1.0789   -1.1103 H          1 UNL      0.452000
@<TRIPOS>BOND
     1    1    2 1
     2    1    8 1
     3    1    9 1
     4    1   10 1
     5    2    3 2
     6    2    4 1
     7    4    5 1
     8    4   11 1
     9    4   12 1
    10    5    6 1
    11    5    7 2
    12    6   13 1
```
```
$ parameterize acetoacetic_acid.mol2 --charge-type None --min-type None --no-dihed --forcefield CGenFF_2b6 --outdir charmm

...

2019-08-19 13:51:13,886 - htmd.parameterization.cli - INFO - === Results ===
2019-08-19 13:51:13,891 - htmd.parameterization.cli - INFO - Write the list of  to charmm/parameters/CGenFF_2b6/arguments.txt
2019-08-19 13:51:13,897 - htmd.parameterization.writers - INFO - Write MOL2 file: charmm/parameters/CGenFF_2b6/mol.mol2
2019-08-19 13:51:13,901 - htmd.parameterization.writers - INFO - Write PDB file: charmm/parameters/CGenFF_2b6/mol.pdb
2019-08-19 13:51:13,903 - htmd.parameterization.writers - INFO - Write COOR file: charmm/parameters/CGenFF_2b6/mol.coor
2019-08-19 13:51:13,906 - htmd.parameterization.writers - INFO - Write PSF file: charmm/parameters/CGenFF_2b6/mol.psf
2019-08-19 13:51:13,908 - htmd.parameterization.writers - INFO - Write RTF file: charmm/parameters/CGenFF_2b6/mol.rtf
Traceback (most recent call last):
  File "/shared/raimis/opt/miniconda/envs/htmd/bin/parameterize", line 11, in <module>
    load_entry_point('htmd', 'console_scripts', 'parameterize')()
  File "/home/raimis/htmd.git/htmd/parameterization/cli.py", line 765, in main_parameterize
    _output_results(mol, parameters, initial_mol.coords, args)
  File "/home/raimis/htmd.git/htmd/parameterization/cli.py", line 552, in _output_results
    writeParameters(paramDir, mol, parameters, args.forcefield, args.charge, original_coords=original_coords)
  File "/home/raimis/htmd.git/htmd/parameterization/writers.py", line 311, in writeParameters
    writePRM(mol, parameters, file_)
  File "/home/raimis/htmd.git/htmd/parameterization/writers.py", line 172, in writePRM
    type, field = findImproperType(type, parameters)
TypeError: 'NoneType' object is not iterable
```
Preliminary debugging indicates that there is something wrong with the order of improper atoms for CHARMM. This works without a problem for AMBER.

**Comment by raimis** [comment]
I found that Parmed is changing improper order:

**Comment by raimis** [comment]
Using the current Parmed 3.2.0: 
```
OrderedDict([(('C2O2', 'C311', 'O302', 'O2D1'), <ImproperType; psi_k=120.000, psi_eq=0.000>), 
             (('C2O2', 'C261', 'O302', 'O2D1'), <ImproperType; psi_k=120.000, psi_eq=0.000>)])
```
