### ISSUE TITLE
parameterize: MM fitting problem

### ISSUE THREAD

**Issue by maicol93** [Acellera/htmd#945]
I tried to use the parameterize tool to optimize the dihedrals of a small molecule, which structure has been herein attached, using the following command:

> parameterize t4g.mol2 --charge 0 --forcefield CGenFF_2b6 --theory HF --basis 6-311G** --min-type mm --scan-type mm --ncpus 16 --outdir results

The tool has correctly completed the QM calculations using psi4, but has stuck in the fitting procedure reporting this error:

> Traceback (most recent call last):
>   File "/home/mbissaro/software/miniconda3-19/bin/parameterize", line 11, in <module>
>     sys.exit(main_parameterize())
>   File "/home/mbissaro/software/miniconda3-19/lib/python3.6/site-packages/htmd/parameterization/cli.py", line 761, in main_parameterize
>     parameters = df.run()
>   File "/home/mbissaro/software/miniconda3-19/lib/python3.6/site-packages/htmd/parameterization/dihedral.py", line 498, in run
>     self._fit()
>   File "/home/mbissaro/software/miniconda3-19/lib/python3.6/site-packages/htmd/parameterization/dihedral.py", line 441, in _fit
>     assert np.allclose(initial_energies, const_energies + actual_enegies, rtol=0, atol=1e-5) # TODO debug
> AssertionError

As read in a previous post, I did not select QM minimization, preferring instead single points calculations. Despite this I could not complete the parameterization. How can I solve the problem?
Thanks
[t4g.mol2.zip](https://github.com/Acellera/htmd/files/3902614/t4g.mol2.zip)

**Comment by raimis** [comment]
@maicol93 

Thanks for reporting, we already encountered this problem and it should be solved by https://github.com/Acellera/htmd/pull/942

**Comment by raimis** [comment]
Try to update HTMD and rerun the command. `parameterize` will reuse the QM results.
