### ISSUE TITLE
import htmd.ui failed

### ISSUE THREAD

**Issue by huanyusb** [Acellera/htmd#949]
I have just install the htmd by conda. 
when I try to import the htmd modual, it returns the following error mesage:
`/home/xxx/anaconda3/envs/htmd2/lib/python3.6/site-packages/htmd/versionwarnings.py:29: UserWarning: As of HTMD 1.16
 the default ACEMD version for all protocols has changed to version 3. If you want to use version 2 protocols chang
e the _version argument in the protocols or add `config(acemdversion=2)` to the beginning of your scripts. To disab
le this warning run once: `from htmd import _disableWarnings; _disableWarnings('1.16');`
  , UserWarning)
/home/xxx/anaconda3/envs/htmd2/lib/python3.6/site-packages/htmd/versionwarnings.py:33: UserWarning: As of HTMD 1.16
 the default number of threads HTMD spawns for calculations is set to 1. You can enable parallelism at your own ris
k using `config(njobs=-2)` in the beginning of your scripts. To disable this warning run once: `from htmd import _d
isableWarnings; _disableWarnings('1.16');`
  , UserWarning)
Traceback (most recent call last):
  File "build.py", line 1, in <module>
    from htmd.ui import *
  File "/home/xxx/anaconda3/envs/htmd2/lib/python3.6/site-packages/htmd/ui.py", line 21, in <module>
    from htmd.projections.tica import TICA
  File "/home/xxx/anaconda3/envs/htmd2/lib/python3.6/site-packages/htmd/projections/tica.py", line 10, in <module>
    from htmd.units import convert as unitconvert
  File "/home/xxx/anaconda3/envs/htmd2/lib/python3.6/site-packages/htmd/units.py", line 6, in <module>
    from pint import UnitRegistry
  File "/home/xxx/anaconda3/envs/htmd2/lib/python3.6/site-packages/pint/__init__.py", line 28, in <module>
    from .measurement import Measurement
  File "/home/xxx/anaconda3/envs/htmd2/lib/python3.6/site-packages/pint/measurement.py", line 12, in <module>
    from .quantity import Quantity
  File "/home/xxx/anaconda3/envs/htmd2/lib/python3.6/site-packages/pint/quantity.py", line 51, in <module>
    from .numpy_func import (
  File "/home/xxx/anaconda3/envs/htmd2/lib/python3.6/site-packages/pint/numpy_func.py", line 831, in <module>
    "function", func_str, input_units="all_consistent", output_unit="match_input"
  File "/home/xxx/anaconda3/envs/htmd2/lib/python3.6/site-packages/pint/numpy_func.py", line 262, in implement_func
    func = getattr(np, func_str_split[0])
AttributeError: module 'numpy' has no attribute 'block'`

It seems that I shoud update the version of numpy, but it report a lot of conflicts when I try to update numpy using `conda install numpy=1.18`

**Comment by stefdoerr** [comment]
Hm there were some issues in releasing HTMD 1.19. I will take a look at it later today

**Comment by stefdoerr** [comment]
Try installing in  new conda environment with 

```
conda create -n my_new_env_name
conda activate my_new_env_name
conda install htmd=1.19 -c acellera -c psi4 -c conda-forge
```
For me it worked without issues

**Comment by huanyusb** [comment]
> Try installing in new conda environment with
> 
> ```
> conda create -n my_new_env_name
> conda activate my_new_env_name
> conda install htmd=1.19 -c acellera -c psi4 -c conda-forge
> ```
> 
> For me it worked without issues

Thanks, it works fine now.

**Comment by stefdoerr** [comment]
Great :) closing the issue then
