### ISSUE TITLE
ValueError in simple build script

### ISSUE THREAD

**Issue by aqred1** [Acellera/htmd#958]
When running the following simple build script: 

```
from htmd.ui import *

mol = Molecule("1THF")
mol.filter("protein and chain A and resid 1 to 226")
mol_op = proteinPrepare(mol)
mol_seg = autoSegment(mol_op)
mol_solv = solvate(mol_seg,pad=8)
mol_charmm = charmm.build(mol_solv)
```

I got the following error:

```
Traceback (most recent call last):
  File "build.py", line 5, in <module>
    mol_op = proteinPrepare(mol)
  File "/agh/projects/miniconda3/envs/htmd1.20.0/lib/python3.6/site-packages/moleculekit/tools/preparation.py", line 363, in proteinPrepare
    _warnIfContainsDUM(mol_in)
  File "/agh/projects/miniconda3/envs/htmd1.20.0/lib/python3.6/site-packages/moleculekit/tools/preparation.py", line 69, in _warnIfContainsDUM
    if any(mol.atomselect("resname DUM")):
  File "/agh/projects/miniconda3/envs/htmd1.20.0/lib/python3.6/site-packages/moleculekit/molecule.py", line 638, in atomselect
    occupancy=self.occupancy, bonds=self._getBonds(fileBonds, guessBonds))
  File "/agh/projects/miniconda3/envs/htmd1.20.0/lib/python3.6/site-packages/moleculekit/vmdparser.py", line 31, in vmdselection
    maxseglen = np.max([len(x) for x in segname])
  File "<__array_function__ internals>", line 6, in amax
  File "/agh/projects/miniconda3/envs/htmd1.20.0/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2668, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/agh/projects/miniconda3/envs/htmd1.20.0/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```
Ideas?

Thanks

**Comment by stefdoerr** [comment]
I am tending towards a broken conda environment since the crash is inside
numpy. But before you delete the environment and create a new one could you
check in vmd if that atomselection works? Do mol.view() to open the exact
molecule and try the atomselection.
Otherwise conda remove yourenv --all and create a new one with htmd.

**Comment by aqred1** [comment]
The selection works in vmd.
I removed the environment and created a new one with this command: `conda create -n htmd1.20.0 htmd=1.20.0 -c acellera -c psi4`
The error persists.

**Comment by stefdoerr** [comment]
Follow the updated instructions on installing htmd. You are missing a
channel in that command.

**Comment by aqred1** [comment]
Thanks, it works now.
