### ISSUE TITLE
Exception in protein protonation

### ISSUE THREAD

**Issue by VincenzoChen** [Acellera/htmd#968]
Hi sir. When I used htmd to do protein protonation by the following code:
```from htmd.ui import *    
protein = Molecule('3PTB')
promol, predata = proteinPrepare(protein,returnDetails=True)
predata.data.to_csv('3PTB.csv')
promol.write('3PTB.pdb')
```
An exception occurred. It said that 
```Traceback (most recent call last):
  File "protonation.py", line 6, in <module>
    promol, predata = proteinPrepare(protein,returnDetails=True)
  File "/home/chenzhao/anaconda3/envs/chemtool/lib/python3.7/site-packages/moleculekit/tools/preparation.py", line 416, in proteinPrepare
    mol_out, resData = _buildResAndMol(pdb2pqr_protein)
  File "/home/chenzhao/anaconda3/envs/chemtool/lib/python3.7/site-packages/moleculekit/tools/preparation.py", line 152, in _buildResAndMol
    prepData._set(residue, 'pdb2pqr_idx', i)
  File "/home/chenzhao/anaconda3/envs/chemtool/lib/python3.7/site-packages/moleculekit/tools/preparationdata.py", line 130, in _set
    pos = self._findRes(residue.name, residue.resSeq, residue.iCode, residue.chainID)
  File "/home/chenzhao/anaconda3/envs/chemtool/lib/python3.7/site-packages/moleculekit/tools/preparationdata.py", line 123, in _findRes
    pos = int(np.argwhere(mask))
  File "<__array_function__ internals>", line 6, in argwhere
  File "/home/chenzhao/anaconda3/envs/chemtool/lib/python3.7/site-packages/numpy/core/numeric.py", line 584, in argwhere
    return transpose(nonzero(a))
  File "<__array_function__ internals>", line 6, in nonzero
  File "/home/chenzhao/anaconda3/envs/chemtool/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1896, in nonzero
    return _wrapfunc(a, 'nonzero')
  File "/home/chenzhao/anaconda3/envs/chemtool/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/chenzhao/anaconda3/envs/chemtool/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapit
    result = wrap(result)
  File "/home/chenzhao/anaconda3/envs/chemtool/lib/python3.7/site-packages/pandas/core/generic.py", line 1918, in __array_wrap__
    return self._constructor(result, **d).__finalize__(self)
  File "/home/chenzhao/anaconda3/envs/chemtool/lib/python3.7/site-packages/pandas/core/series.py", line 305, in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
  File "/home/chenzhao/anaconda3/envs/chemtool/lib/python3.7/site-packages/pandas/core/construction.py", line 482, in sanitize_array
    raise Exception("Data must be 1-dimensional")
Exception: Data must be 1-dimensional
```
The pandas I am using is 1.0.5 version which I think may be the reason to this problem.

**Comment by stefdoerr** [comment]
Yes this could be it. Is there a reason why you want to use pantas 1.0.5? They changed a lot of their API so I'm not sure we support it yet.
What versions of htmd / htmd-pdb2pqr are you using? Try doing `conda list htmd-pdb2pqr`, `conda list htmd`.

**Comment by VincenzoChen** [comment]
Here are the vision information:
```
# Name                    Version                   Build  Channel
htmd                      1.22.4                   py37_0    acellera
htmd-deps                 1.22.4                   py37_0    acellera
htmd-pdb2pqr              2.1.1+htmd.14              py_0    acellera
```
This problem was solved when I downgrade my pandas to 0.25.3.

**Comment by stefdoerr** [comment]
But did you manually install a higher pandas version? I think HTMD should by default pull a pandas version under v1.
If there is real need to move to pandas >1 I could look at updating HTMD

**Comment by VincenzoChen** [comment]
I didn't install a higher pandas version manually. Actually when I used conda to install HTMD, it installed the pandas=1.0.5 defaultly.

**Comment by stefdoerr** [comment]
Should be fixed in the latest HTMD version which asks for an older pandas
